# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: acls.ipv6
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_acls_ipv6 = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].acls.ipv6, []) : {
        key         = format("%s/ipv6/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        fragments        = try(item.fragments,
          null)
        statistics_per_entry = try(item.statistics_per_entry,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ipv6_nxos ----
resource "nso_device_config" "ipv6_nxos" {
  for_each = { for v in local.nso_acls_ipv6 : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ipv6/access-list/list-name=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.fragments != null ? { "fragments" = each.value.fragments } : {},
    each.value.statistics_per_entry == true ? { "statistics/per-entry" = "" } : {},
  )
}
# ---- END GENERATED resource ipv6_nxos ----
# ---- BEGIN GENERATED resource ipv6_iosxe ----
resource "nso_device_config" "ipv6_iosxe" {
  for_each = { for v in local.nso_acls_ipv6 : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ipv6/access-list/named-acl=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource ipv6_iosxe ----

