# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.radius_servers
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_radius_servers = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_radius_servers, []) : {
        key         = format("%s/radius_server/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        address_ipv4     = try(item.address_ipv4,
          null)
        auth_port        = try(item.auth_port,
          null)
        acct_port        = try(item.acct_port,
          null)
        timeout          = try(item.timeout,
          null)
        retransmit       = try(item.retransmit,
          null)
        key_type         = try(item.key_type,
          null)
        key_secret       = try(item.key_secret,
          null)
        key_encryption   = try(item.key_encryption,
          null)
        key_password     = try(item.key_password,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource radius_server_nxos ----
resource "nso_device_config" "radius_server_nxos" {
  for_each = { for v in local.nso_aaa_radius_servers : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:radius-server/host=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.auth_port != null ? { "auth-port" = each.value.auth_port } : {},
    each.value.acct_port != null ? { "acct-port" = each.value.acct_port } : {},
    each.value.timeout != null ? { "timeout" = each.value.timeout } : {},
    each.value.retransmit != null ? { "retransmit" = each.value.retransmit } : {},
    each.value.key_encryption != null ? { "key/encryption" = each.value.key_encryption } : {},
    each.value.key_password != null ? { "key/password" = each.value.key_password } : {},
  )
}
# ---- END GENERATED resource radius_server_nxos ----
# ---- BEGIN GENERATED resource radius_server_iosxe ----
resource "nso_device_config" "radius_server_iosxe" {
  for_each = { for v in local.nso_aaa_radius_servers : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:radius/server=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.address_ipv4 != null ? { "address/ipv4/host" = each.value.address_ipv4 } : {},
    each.value.auth_port != null ? { "address/ipv4/auth-port" = each.value.auth_port } : {},
    each.value.acct_port != null ? { "address/ipv4/acct-port" = each.value.acct_port } : {},
    each.value.timeout != null ? { "timeout" = each.value.timeout } : {},
    each.value.retransmit != null ? { "retransmit" = each.value.retransmit } : {},
    each.value.key_type != null ? { "key/key/type" = each.value.key_type } : {},
    each.value.key_secret != null ? { "key/key/secret" = each.value.key_secret } : {},
  )
}
# ---- END GENERATED resource radius_server_iosxe ----

