# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: management.ip_http
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_management_ip_http = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].ip_http, []) : {
        key         = format("%s/ip_http/%s", device.name, item.ip_http)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        ip_http  = item.ip_http
        server           = try(item.server,
          null)
        secure_server    = try(item.secure_server,
          null)
        port             = try(item.port,
          null)
        secure_trustpoint = try(item.secure_trustpoint,
          null)
        tls_version      = try(item.tls_version,
          null)
        max_connections  = try(item.max_connections,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ip_http_iosxe ----
resource "nso_device_config" "ip_http_iosxe" {
  for_each = { for v in local.nso_management_ip_http : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/http"
  delete   = true

  attributes = merge(
    { http = tostring(each.value.ip_http) },
    each.value.server != null ? { "server" = each.value.server } : {},
    each.value.secure_server != null ? { "secure-server" = each.value.secure_server } : {},
    each.value.port != null ? { "port" = each.value.port } : {},
    each.value.secure_trustpoint != null ? { "secure-trustpoint" = each.value.secure_trustpoint } : {},
    each.value.tls_version != null ? { "tls-version" = each.value.tls_version } : {},
    each.value.max_connections != null ? { "max-connections" = each.value.max_connections } : {},
  )
}
# ---- END GENERATED resource ip_http_iosxe ----

