# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.authentication_login_default
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_authentication_login_default = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_authentication_login_default, []) : {
        key         = format("%s/authentication_login_default/%s", device.name, item.aaa_authentication_login_default)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        aaa_authentication_login_default  = item.aaa_authentication_login_default
        group            = try(item.group,
          null)
        group2           = try(item.group2,
          null)
        group3           = try(item.group3,
          null)
        fallback         = try(item.fallback,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource authentication_login_default_nxos ----
resource "nso_device_config" "authentication_login_default_nxos" {
  for_each = { for v in local.nso_aaa_authentication_login_default : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:aaa/authentication/login/default"
  delete   = true

  attributes = merge(
    { aaa_authentication_login_default = tostring(each.value.aaa_authentication_login_default) },
    each.value.group != null ? { "group" = each.value.group } : {},
    each.value.group2 != null ? { "group2" = each.value.group2 } : {},
    each.value.group3 != null ? { "group3" = each.value.group3 } : {},
    each.value.fallback != null ? { "fallback" = each.value.fallback } : {},
  )
}
# ---- END GENERATED resource authentication_login_default_nxos ----

