# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: routing.eigrp
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_routing_eigrp = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].routing.eigrp, []) : {
        key         = format("%s/eigrp/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        router_id        = try(item.router_id,
          null)
        autonomous_system = try(item.autonomous_system,
          null)
        maximum_paths    = try(item.maximum_paths,
          null)
        variance         = try(item.variance,
          null)
        distance_internal = try(item.distance_internal,
          null)
        distance_external = try(item.distance_external,
          null)
        bfd              = try(item.bfd,
          null)
        passive_interface_default = try(item.passive_interface_default,
          null)
        log_adjacency_changes = try(item.log_adjacency_changes,
          null)
        log_neighbor_warnings = try(item.log_neighbor_warnings,
          null)
        log_neighbor_changes = try(item.log_neighbor_changes,
          null)
        eigrp_stub_connected = try(item.eigrp_stub_connected,
          null)
        eigrp_stub_static = try(item.eigrp_stub_static,
          null)
        eigrp_stub_summary = try(item.eigrp_stub_summary,
          null)
        eigrp_stub_redistributed = try(item.eigrp_stub_redistributed,
          null)
        auto_summary     = try(item.auto_summary,
          null)
        nsf              = try(item.nsf,
          null)
        metric_maximum_hops = try(item.metric_maximum_hops,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource eigrp_nxos ----
resource "nso_device_config" "eigrp_nxos" {
  for_each = { for v in local.nso_routing_eigrp : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:router/eigrp=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.router_id != null ? { "router-id" = each.value.router_id } : {},
    each.value.autonomous_system != null ? { "autonomous-system" = each.value.autonomous_system } : {},
    each.value.maximum_paths != null ? { "maximum-paths" = each.value.maximum_paths } : {},
    each.value.distance_internal != null ? { "distance/internal" = each.value.distance_internal } : {},
    each.value.distance_external != null ? { "distance/external" = each.value.distance_external } : {},
    each.value.bfd == true ? { "bfd" = "" } : {},
    each.value.passive_interface_default == true ? { "passive-interface/default" = "" } : {},
    each.value.log_adjacency_changes != null ? { "log-adjacency-changes" = each.value.log_adjacency_changes } : {},
    each.value.log_neighbor_warnings != null ? { "log-neighbor-warnings" = each.value.log_neighbor_warnings } : {},
  )
}
# ---- END GENERATED resource eigrp_nxos ----
# ---- BEGIN GENERATED resource eigrp_iosxe ----
resource "nso_device_config" "eigrp_iosxe" {
  for_each = { for v in local.nso_routing_eigrp : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:router/eigrp=${each.value.id}"
  delete   = true

  attributes = merge(
    { as-no = tostring(each.value.id) },
    each.value.router_id != null ? { "eigrp/router-id" = each.value.router_id } : {},
    each.value.maximum_paths != null ? { "maximum-paths" = each.value.maximum_paths } : {},
    each.value.variance != null ? { "variance" = each.value.variance } : {},
    each.value.distance_internal != null ? { "distance/eigrp/internal-distance" = each.value.distance_internal } : {},
    each.value.distance_external != null ? { "distance/eigrp/external-distance" = each.value.distance_external } : {},
    each.value.bfd == true ? { "bfd/all-interfaces" = "" } : {},
    each.value.passive_interface_default == true ? { "passive-interface/default" = "" } : {},
    each.value.log_neighbor_changes != null ? { "eigrp/log-neighbor-changes" = each.value.log_neighbor_changes } : {},
    each.value.eigrp_stub_connected == true ? { "eigrp/stub/connected" = "" } : {},
    each.value.eigrp_stub_static == true ? { "eigrp/stub/static" = "" } : {},
    each.value.eigrp_stub_summary == true ? { "eigrp/stub/summary" = "" } : {},
    each.value.eigrp_stub_redistributed == true ? { "eigrp/stub/redistributed" = "" } : {},
    each.value.auto_summary == true ? { "auto-summary" = "" } : {},
    each.value.nsf == true ? { "nsf" = "" } : {},
    each.value.metric_maximum_hops != null ? { "metric/maximum-hops" = each.value.metric_maximum_hops } : {},
  )
}
# ---- END GENERATED resource eigrp_iosxe ----

