# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.accounting_default
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_accounting_default = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_accounting_default, []) : {
        key         = format("%s/accounting_default/%s", device.name, item.aaa_accounting_default)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        aaa_accounting_default  = item.aaa_accounting_default
        group            = try(item.group,
          null)
        local            = try(item.local,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource accounting_default_nxos ----
resource "nso_device_config" "accounting_default_nxos" {
  for_each = { for v in local.nso_aaa_accounting_default : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:aaa/accounting/default"
  delete   = true

  attributes = merge(
    { aaa_accounting_default = tostring(each.value.aaa_accounting_default) },
    each.value.group != null ? { "group" = each.value.group } : {},
    each.value.local != null ? { "local" = each.value.local } : {},
  )
}
# ---- END GENERATED resource accounting_default_nxos ----

