# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dhcp.relay
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dhcp_relay = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dhcp.relay, []) : {
        key         = format("%s/relay/%s", device.name, item.relay)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        relay  = item.relay
        enabled          = try(item.enabled,
          null)
        information_option_vpn = try(item.information_option_vpn,
          null)
        information_trust_all = try(item.information_trust_all,
          null)
        information_check = try(item.information_check,
          null)
        information_option_trust = try(item.information_option_trust,
          null)
        sub_option_type_cisco = try(item.sub_option_type_cisco,
          null)
        override_giaddr_link_selection = try(item.override_giaddr_link_selection,
          null)
        prefer_known_good_server = try(item.prefer_known_good_server,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource relay_nxos ----
resource "nso_device_config" "relay_nxos" {
  for_each = { for v in local.nso_dhcp_relay : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip/dhcp"
  delete   = true

  attributes = merge(
    { relay = tostring(each.value.relay) },
    each.value.enabled != null ? { "relay" = each.value.enabled } : {},
    each.value.information_option_vpn == true ? { "relay-config/relay/information/option/vpn" = "" } : {},
    each.value.information_trust_all == true ? { "relay-config/relay/information/trust-all" = "" } : {},
    each.value.information_option_trust == true ? { "relay-config/relay/information/option/trust" = "" } : {},
    each.value.sub_option_type_cisco == true ? { "relay-config/relay/sub-option/type/cisco" = "" } : {},
  )
}
# ---- END GENERATED resource relay_nxos ----
# ---- BEGIN GENERATED resource relay_iosxe ----
resource "nso_device_config" "relay_iosxe" {
  for_each = { for v in local.nso_dhcp_relay : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/dhcp"
  delete   = true

  attributes = merge(
    { relay = tostring(each.value.relay) },
    each.value.information_option_vpn == true ? { "relay/information/option-conf/option/vpn" = "" } : {},
    each.value.information_trust_all == true ? { "relay/information/trust-all" = "" } : {},
    each.value.information_check != null ? { "relay/information/check" = each.value.information_check } : {},
    each.value.override_giaddr_link_selection == true ? { "relay/override/giaddr/link-selection" = "" } : {},
    each.value.prefer_known_good_server == true ? { "relay/prefer/known-good-server" = "" } : {},
  )
}
# ---- END GENERATED resource relay_iosxe ----

