# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.snmp
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_snmp = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].snmp, []) : {
        key         = format("%s/snmp/%s", device.name, item.snmp)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        snmp  = item.snmp
        contact          = try(item.contact,
          null)
        location         = try(item.location,
          null)
        packetsize       = try(item.packetsize,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource snmp_nxos ----
resource "nso_device_config" "snmp_nxos" {
  for_each = { for v in local.nso_system_snmp : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:snmp-server"
  delete   = true

  attributes = merge(
    { snmp = tostring(each.value.snmp) },
    each.value.contact != null ? { "contact" = each.value.contact } : {},
    each.value.location != null ? { "location" = each.value.location } : {},
    each.value.packetsize != null ? { "packetsize" = each.value.packetsize } : {},
  )
}
# ---- END GENERATED resource snmp_nxos ----
# ---- BEGIN GENERATED resource snmp_iosxe ----
resource "nso_device_config" "snmp_iosxe" {
  for_each = { for v in local.nso_system_snmp : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:snmp-server"
  delete   = true

  attributes = merge(
    { snmp = tostring(each.value.snmp) },
    each.value.contact != null ? { "contact" = each.value.contact } : {},
    each.value.location != null ? { "location" = each.value.location } : {},
    each.value.packetsize != null ? { "packetsize" = each.value.packetsize } : {},
  )
}
# ---- END GENERATED resource snmp_iosxe ----

