# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: vpc.domain
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_vpc_domain = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].vpc.domain, []) : {
        key         = format("%s/domain/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        role_priority    = try(item.role_priority,
          null)
        system_priority  = try(item.system_priority,
          null)
        peer_switch      = try(item.peer_switch,
          null)
        peer_gateway     = try(item.peer_gateway,
          null)
        layer3_peer_router = try(item.layer3_peer_router,
          null)
        fast_convergence = try(item.fast_convergence,
          null)
        graceful_consistency_check = try(item.graceful_consistency_check,
          null)
        ip_arp_synchronize = try(item.ip_arp_synchronize,
          null)
        ipv6_nd_synchronize = try(item.ipv6_nd_synchronize,
          null)
        shutdown         = try(item.shutdown,
          null)
        peer_config_check_bypass = try(item.peer_config_check_bypass,
          null)
        track            = try(item.track,
          null)
        auto_recovery_reload_delay = try(item.auto_recovery_reload_delay,
          null)
        delay_restore    = try(item.delay_restore,
          null)
        delay_restore_interface_vlan = try(item.delay_restore_interface_vlan,
          null)
        delay_restore_orphan_port = try(item.delay_restore_orphan_port,
          null)
        peer_keepalive_destination = try(item.peer_keepalive_destination,
          null)
        peer_keepalive_source = try(item.peer_keepalive_source,
          null)
        peer_keepalive_udp_port = try(item.peer_keepalive_udp_port,
          null)
        peer_keepalive_vrf = try(item.peer_keepalive_vrf,
          null)
        peer_keepalive_interval = try(item.peer_keepalive_interval,
          null)
        peer_keepalive_timeout = try(item.peer_keepalive_timeout,
          null)
        peer_keepalive_precedence = try(item.peer_keepalive_precedence,
          null)
        peer_keepalive_hold_timeout = try(item.peer_keepalive_hold_timeout,
          null)
        virtual_peer_link_destination = try(item.virtual_peer_link_destination,
          null)
        virtual_peer_link_source = try(item.virtual_peer_link_source,
          null)
        virtual_peer_link_dscp = try(item.virtual_peer_link_dscp,
          null)
        dual_active_exclude_interface_vlan = try(item.dual_active_exclude_interface_vlan,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource domain_nxos ----
resource "nso_device_config" "domain_nxos" {
  for_each = { for v in local.nso_vpc_domain : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:vpc/domain"
  delete   = false

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.role_priority != null ? { "role/priority" = each.value.role_priority } : {},
    each.value.system_priority != null ? { "system-priority" = each.value.system_priority } : {},
    each.value.peer_switch == true ? { "peer-switch" = "" } : {},
    each.value.peer_gateway == true ? { "peer-gateway" = "" } : {},
    each.value.layer3_peer_router == true ? { "layer3/peer-router" = "" } : {},
    each.value.fast_convergence == true ? { "fast-convergence" = "" } : {},
    each.value.graceful_consistency_check == true ? { "graceful/consistency-check" = "" } : {},
    each.value.ip_arp_synchronize != null ? { "ip/arp" = each.value.ip_arp_synchronize } : {},
    each.value.ipv6_nd_synchronize == true ? { "ipv6/nd/synchronize" = "" } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.peer_config_check_bypass == true ? { "peer-config-check-bypass" = "" } : {},
    each.value.track != null ? { "track" = each.value.track } : {},
    each.value.auto_recovery_reload_delay != null ? { "auto-recovery/auto-recovery/reload-delay" = each.value.auto_recovery_reload_delay } : {},
    each.value.delay_restore != null ? { "delay/restore" = each.value.delay_restore } : {},
    each.value.delay_restore_interface_vlan != null ? { "delay/other-delay/restore/interface-vlan" = each.value.delay_restore_interface_vlan } : {},
    each.value.delay_restore_orphan_port != null ? { "delay/other-delay/restore/orphan-port" = each.value.delay_restore_orphan_port } : {},
    each.value.peer_keepalive_destination != null ? { "peer-keepalive/destination" = each.value.peer_keepalive_destination } : {},
    each.value.peer_keepalive_source != null ? { "peer-keepalive/source" = each.value.peer_keepalive_source } : {},
    each.value.peer_keepalive_udp_port != null ? { "peer-keepalive/udp-port" = each.value.peer_keepalive_udp_port } : {},
    each.value.peer_keepalive_vrf != null ? { "peer-keepalive/vrf" = each.value.peer_keepalive_vrf } : {},
    each.value.peer_keepalive_interval != null ? { "peer-keepalive/interval" = each.value.peer_keepalive_interval } : {},
    each.value.peer_keepalive_timeout != null ? { "peer-keepalive/timeout" = each.value.peer_keepalive_timeout } : {},
    each.value.peer_keepalive_precedence != null ? { "peer-keepalive/precedence" = each.value.peer_keepalive_precedence } : {},
    each.value.peer_keepalive_hold_timeout != null ? { "peer-keepalive/hold-timeout" = each.value.peer_keepalive_hold_timeout } : {},
    each.value.virtual_peer_link_destination != null ? { "virtual/peer-link/destination" = each.value.virtual_peer_link_destination } : {},
    each.value.virtual_peer_link_source != null ? { "virtual/peer-link/source" = each.value.virtual_peer_link_source } : {},
    each.value.virtual_peer_link_dscp != null ? { "virtual/peer-link/dscp" = each.value.virtual_peer_link_dscp } : {},
    each.value.dual_active_exclude_interface_vlan != null ? { "dual-active/exclude/interface-vlan" = each.value.dual_active_exclude_interface_vlan } : {},
  )
}
# ---- END GENERATED resource domain_nxos ----

