# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: static_routes.ipv4_interface_only
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_static_routes_ipv4_interface_only = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].static_routes.ipv4_interface_only, []) : {
        key         = format("%s/ipv4_interface_only/%s", device.name, item.composite)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        composite  = item.composite
        prefix           = try(item.prefix,
          null)
        mask             = try(item.mask,
          null)
        interface        = try(item.interface,
          null)
        name             = try(item.name,
          null)
        tag              = try(item.tag,
          null)
        distance         = try(item.distance,
          null)
        track            = try(item.track,
          null)
        permanent        = try(item.permanent,
          null)
        multicast        = try(item.multicast,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ipv4_interface_only_iosxe ----
resource "nso_device_config" "ipv4_interface_only_iosxe" {
  for_each = { for v in local.nso_static_routes_ipv4_interface_only : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/route/ip-route-interface-list={prefix},{mask},{interface}"
  delete   = true

  attributes = merge(
    { prefix,mask,interface = tostring(each.value.composite) },
    each.value.prefix != null ? { "prefix" = each.value.prefix } : {},
    each.value.mask != null ? { "mask" = each.value.mask } : {},
    each.value.interface != null ? { "interface" = each.value.interface } : {},
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.tag != null ? { "tag" = each.value.tag } : {},
    each.value.distance != null ? { "metric" = each.value.distance } : {},
    each.value.track != null ? { "track" = each.value.track } : {},
    each.value.permanent == true ? { "permanent" = "" } : {},
    each.value.multicast == true ? { "multicast" = "" } : {},
  )
}
# ---- END GENERATED resource ipv4_interface_only_iosxe ----

