# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: vxlan.nve_interfaces
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_vxlan_nve_interfaces = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].vxlan.nve_interfaces, []) : {
        key         = format("%s/nve_interface/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        description      = try(item.description,
          null)
        shutdown         = try(item.shutdown,
          null)
        source_interface = try(item.source_interface,
          null)
        source_interface_anycast = try(item.source_interface_anycast,
          null)
        host_reachability_protocol = try(item.host_reachability_protocol,
          null)
        overlay_encapsulation = try(item.overlay_encapsulation,
          null)
        global_ingress_replication_protocol = try(item.global_ingress_replication_protocol,
          null)
        global_suppress_arp = try(item.global_suppress_arp,
          null)
        global_mcast_group = try(item.global_mcast_group,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource nve_interface_nxos ----
resource "nso_device_config" "nve_interface_nxos" {
  for_each = { for v in local.nso_vxlan_nve_interfaces : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:interface/nve=${each.value.id}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.id) },
    each.value.id != null ? { "name" = each.value.id } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.source_interface != null ? { "source-interface/name" = each.value.source_interface } : {},
    each.value.source_interface_anycast != null ? { "source-interface/anycast" = each.value.source_interface_anycast } : {},
    each.value.host_reachability_protocol != null ? { "host-reachability/protocol" = each.value.host_reachability_protocol } : {},
    each.value.overlay_encapsulation != null ? { "overlay-encapsulation" = each.value.overlay_encapsulation } : {},
    each.value.global_ingress_replication_protocol != null ? { "global/ingress-replication/protocol" = each.value.global_ingress_replication_protocol } : {},
    each.value.global_suppress_arp == true ? { "global/suppress-arp" = "" } : {},
    each.value.global_mcast_group != null ? { "global/mcast-group/mcast-addr" = each.value.global_mcast_group } : {},
  )
}
# ---- END GENERATED resource nve_interface_nxos ----
# ---- BEGIN GENERATED resource nve_interface_iosxe ----
resource "nso_device_config" "nve_interface_iosxe" {
  for_each = { for v in local.nso_vxlan_nve_interfaces : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:interface/nve=${each.value.id}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.id) },
    each.value.id != null ? { "name" = each.value.id } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.source_interface != null ? { "source-interface/Loopback/Loopback" = each.value.source_interface } : {},
    each.value.host_reachability_protocol == true ? { "host-reachability/protocol/bgp" = "" } : {},
  )
}
# ---- END GENERATED resource nve_interface_iosxe ----

