# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: static_routes.ipv6_next_hop
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_static_routes_ipv6_next_hop = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].static_routes.ipv6_next_hop, []) : {
        key         = format("%s/ipv6_next_hop/%s", device.name, item.composite)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        composite  = item.composite
        prefix           = try(item.prefix,
          null)
        next_hop         = try(item.next_hop,
          null)
        name             = try(item.name,
          null)
        tag              = try(item.tag,
          null)
        distance         = try(item.distance,
          null)
        track            = try(item.track,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ipv6_next_hop_nxos ----
resource "nso_device_config" "ipv6_next_hop_nxos" {
  for_each = { for v in local.nso_static_routes_ipv6_next_hop : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ipv6/route/ipv6-route-list={prefix-mask},{next-hop}"
  delete   = true

  attributes = merge(
    { prefix-mask,next-hop = tostring(each.value.composite) },
    each.value.prefix != null ? { "prefix-mask" = each.value.prefix } : {},
    each.value.next_hop != null ? { "next-hop" = each.value.next_hop } : {},
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.tag != null ? { "tag" = each.value.tag } : {},
    each.value.distance != null ? { "preference" = each.value.distance } : {},
    each.value.track != null ? { "track" = each.value.track } : {},
  )
}
# ---- END GENERATED resource ipv6_next_hop_nxos ----
# ---- BEGIN GENERATED resource ipv6_next_hop_iosxe ----
resource "nso_device_config" "ipv6_next_hop_iosxe" {
  for_each = { for v in local.nso_static_routes_ipv6_next_hop : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ipv6/route/no-vrf/ipv6-route-destination-list={prefix},{destination}"
  delete   = true

  attributes = merge(
    { prefix,destination = tostring(each.value.composite) },
    each.value.prefix != null ? { "prefix" = each.value.prefix } : {},
    each.value.next_hop != null ? { "destination" = each.value.next_hop } : {},
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.tag != null ? { "tag" = each.value.tag } : {},
    each.value.distance != null ? { "distance" = each.value.distance } : {},
    each.value.track != null ? { "track" = each.value.track } : {},
  )
}
# ---- END GENERATED resource ipv6_next_hop_iosxe ----

