# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.service
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_service = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].service, []) : {
        key         = format("%s/service/%s", device.name, item.service)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        service  = item.service
        tcp_keepalives_in = try(item.tcp_keepalives_in,
          null)
        tcp_keepalives_out = try(item.tcp_keepalives_out,
          null)
        config           = try(item.config,
          null)
        nagle            = try(item.nagle,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource service_iosxe ----
resource "nso_device_config" "service_iosxe" {
  for_each = { for v in local.nso_system_service : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:service"
  delete   = true

  attributes = merge(
    { service = tostring(each.value.service) },
    each.value.tcp_keepalives_in == true ? { "tcp-keepalives-in" = "" } : {},
    each.value.tcp_keepalives_out == true ? { "tcp-keepalives-out" = "" } : {},
    each.value.config == true ? { "config" = "" } : {},
    each.value.nagle == true ? { "nagle" = "" } : {},
  )
}
# ---- END GENERATED resource service_iosxe ----

