# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.tacacs_servers
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_tacacs_servers = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_tacacs_servers, []) : {
        key         = format("%s/tacacs_server/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        address_ipv4     = try(item.address_ipv4,
          null)
        port             = try(item.port,
          null)
        timeout          = try(item.timeout,
          null)
        key_type         = try(item.key_type,
          null)
        key_secret       = try(item.key_secret,
          null)
        key_encryption   = try(item.key_encryption,
          null)
        shared_secret    = try(item.shared_secret,
          null)
        single_connection = try(item.single_connection,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource tacacs_server_nxos ----
resource "nso_device_config" "tacacs_server_nxos" {
  for_each = { for v in local.nso_aaa_tacacs_servers : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:tacacs-server/host=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.port != null ? { "port" = each.value.port } : {},
    each.value.timeout != null ? { "timeout" = each.value.timeout } : {},
    each.value.key_encryption != null ? { "secret/key" = each.value.key_encryption } : {},
    each.value.shared_secret != null ? { "secret/shared-secret" = each.value.shared_secret } : {},
  )
}
# ---- END GENERATED resource tacacs_server_nxos ----
# ---- BEGIN GENERATED resource tacacs_server_iosxe ----
resource "nso_device_config" "tacacs_server_iosxe" {
  for_each = { for v in local.nso_aaa_tacacs_servers : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:tacacs/server=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.address_ipv4 != null ? { "address/ipv4" = each.value.address_ipv4 } : {},
    each.value.port != null ? { "port" = each.value.port } : {},
    each.value.timeout != null ? { "timeout" = each.value.timeout } : {},
    each.value.key_type != null ? { "key/type" = each.value.key_type } : {},
    each.value.key_secret != null ? { "key/secret" = each.value.key_secret } : {},
    each.value.single_connection == true ? { "single-connection" = "" } : {},
  )
}
# ---- END GENERATED resource tacacs_server_iosxe ----

