# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: acls.ipv4_settings
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_acls_ipv4_settings = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].acls.ipv4_settings, []) : {
        key         = format("%s/ipv4_setting/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        logging_interval = try(item.logging_interval,
          null)
        logging_hash_generation = try(item.logging_hash_generation,
          null)
        persistent       = try(item.persistent,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ipv4_setting_iosxe ----
resource "nso_device_config" "ipv4_setting_iosxe" {
  for_each = { for v in local.nso_acls_ipv4_settings : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/access-list"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "." = each.value.id } : {},
    each.value.logging_interval != null ? { "logging/interval" = each.value.logging_interval } : {},
    each.value.logging_hash_generation == true ? { "logging/hash-generation" = "" } : {},
    each.value.persistent == true ? { "persistent" = "" } : {},
  )
}
# ---- END GENERATED resource ipv4_setting_iosxe ----

