# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: qos.class_maps
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_qos_class_maps = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].qos.class_maps, []) : {
        key         = format("%s/class_map/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        prematch         = try(item.prematch,
          null)
        description      = try(item.description,
          null)
        type             = try(item.type,
          null)
        protocol         = try(item.protocol,
          null)
        match_any        = try(item.match_any,
          null)
        match_dscp       = try(item.match_dscp,
          null)
        match_cos        = try(item.match_cos,
          null)
        match_precedence = try(item.match_precedence,
          null)
        match_qos_group  = try(item.match_qos_group,
          null)
        match_vlan       = try(item.match_vlan,
          null)
        match_ip_dscp    = try(item.match_ip_dscp,
          null)
        match_ip_precedence = try(item.match_ip_precedence,
          null)
        match_access_group_name = try(item.match_access_group_name,
          null)
        match_access_group_index = try(item.match_access_group_index,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource class_map_iosxe ----
resource "nso_device_config" "class_map_iosxe" {
  for_each = { for v in local.nso_qos_class_maps : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:class-map=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.prematch != null ? { "prematch" = each.value.prematch } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.type != null ? { "type" = each.value.type } : {},
    each.value.protocol != null ? { "protocol" = each.value.protocol } : {},
    each.value.match_any == true ? { "match/any" = "" } : {},
    each.value.match_dscp != null ? { "match/dscp" = each.value.match_dscp } : {},
    each.value.match_cos != null ? { "match/cos" = each.value.match_cos } : {},
    each.value.match_precedence != null ? { "match/precedence" = each.value.match_precedence } : {},
    each.value.match_qos_group != null ? { "match/qos-group" = each.value.match_qos_group } : {},
    each.value.match_vlan != null ? { "match/vlan" = each.value.match_vlan } : {},
    each.value.match_ip_dscp != null ? { "match/ip/dscp" = each.value.match_ip_dscp } : {},
    each.value.match_ip_precedence != null ? { "match/ip/precedence" = each.value.match_ip_precedence } : {},
    each.value.match_access_group_name != null ? { "match/access-group/name" = each.value.match_access_group_name } : {},
    each.value.match_access_group_index != null ? { "match/access-group/index" = each.value.match_access_group_index } : {},
  )
}
# ---- END GENERATED resource class_map_iosxe ----

