# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: acls.mac
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_acls_mac = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].acls.mac, []) : {
        key         = format("%s/mac/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        statistics_per_entry = try(item.statistics_per_entry,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource mac_nxos ----
resource "nso_device_config" "mac_nxos" {
  for_each = { for v in local.nso_acls_mac : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:mac/access-list/list-name=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.statistics_per_entry == true ? { "statistics/per-entry" = "" } : {},
  )
}
# ---- END GENERATED resource mac_nxos ----
# ---- BEGIN GENERATED resource mac_iosxe ----
resource "nso_device_config" "mac_iosxe" {
  for_each = { for v in local.nso_acls_mac : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:mac/access-list/extended=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
  )
}
# ---- END GENERATED resource mac_iosxe ----

