# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: routing.ospf
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_routing_ospf = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].routing.ospf, []) : {
        key         = format("%s/ospf/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        router_id        = try(item.router_id,
          null)
        log_adjacency_changes = try(item.log_adjacency_changes,
          null)
        default_information_originate = try(item.default_information_originate,
          null)
        bfd              = try(item.bfd,
          null)
        auto_cost_reference_bandwidth = try(item.auto_cost_reference_bandwidth,
          null)
        maximum_paths    = try(item.maximum_paths,
          null)
        default_metric   = try(item.default_metric,
          null)
        distance         = try(item.distance,
          null)
        passive_interface_default = try(item.passive_interface_default,
          null)
        graceful_restart = try(item.graceful_restart,
          null)
        rfc1583_compatibility = try(item.rfc1583_compatibility,
          null)
        default_information_originate_always = try(item.default_information_originate_always,
          null)
        timers_throttle_spf_initial = try(item.timers_throttle_spf_initial,
          null)
        timers_throttle_spf_min_hold = try(item.timers_throttle_spf_min_hold,
          null)
        timers_throttle_spf_max_wait = try(item.timers_throttle_spf_max_wait,
          null)
        timers_throttle_lsa_start = try(item.timers_throttle_lsa_start,
          null)
        timers_throttle_lsa_hold = try(item.timers_throttle_lsa_hold,
          null)
        timers_throttle_lsa_max = try(item.timers_throttle_lsa_max,
          null)
        isolate          = try(item.isolate,
          null)
        name_lookup      = try(item.name_lookup,
          null)
        flush_routes     = try(item.flush_routes,
          null)
        nsr              = try(item.nsr,
          null)
        shutdown         = try(item.shutdown,
          null)
        priority         = try(item.priority,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ospf_nxos ----
resource "nso_device_config" "ospf_nxos" {
  for_each = { for v in local.nso_routing_ospf : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:router/ospf=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.router_id != null ? { "router-id" = each.value.router_id } : {},
    each.value.log_adjacency_changes == true ? { "log-adjacency-changes" = "" } : {},
    each.value.default_information_originate == true ? { "default-information/originate" = "" } : {},
    each.value.bfd == true ? { "bfd" = "" } : {},
    each.value.auto_cost_reference_bandwidth != null ? { "auto-cost/reference-bandwidth" = each.value.auto_cost_reference_bandwidth } : {},
    each.value.maximum_paths != null ? { "maximum-paths" = each.value.maximum_paths } : {},
    each.value.default_metric != null ? { "default-metric" = each.value.default_metric } : {},
    each.value.distance != null ? { "distance" = each.value.distance } : {},
    each.value.passive_interface_default == true ? { "passive-interface/default" = "" } : {},
    each.value.graceful_restart != null ? { "graceful-restart" = each.value.graceful_restart } : {},
    each.value.rfc1583_compatibility == true ? { "rfc1583compatibility" = "" } : {},
    each.value.default_information_originate_always == true ? { "default-information/originate/always" = "" } : {},
    each.value.timers_throttle_spf_initial != null ? { "timers/throttle/spf/initial" = each.value.timers_throttle_spf_initial } : {},
    each.value.timers_throttle_spf_min_hold != null ? { "timers/throttle/spf/minimum" = each.value.timers_throttle_spf_min_hold } : {},
    each.value.timers_throttle_spf_max_wait != null ? { "timers/throttle/spf/maximum" = each.value.timers_throttle_spf_max_wait } : {},
    each.value.timers_throttle_lsa_start != null ? { "timers/throttle/lsa/start" = each.value.timers_throttle_lsa_start } : {},
    each.value.timers_throttle_lsa_hold != null ? { "timers/throttle/lsa/hold" = each.value.timers_throttle_lsa_hold } : {},
    each.value.timers_throttle_lsa_max != null ? { "timers/throttle/lsa/max" = each.value.timers_throttle_lsa_max } : {},
    each.value.isolate == true ? { "isolate" = "" } : {},
    each.value.name_lookup == true ? { "name-lookup" = "" } : {},
    each.value.flush_routes == true ? { "flush-routes" = "" } : {},
  )
}
# ---- END GENERATED resource ospf_nxos ----
# ---- BEGIN GENERATED resource ospf_iosxe ----
resource "nso_device_config" "ospf_iosxe" {
  for_each = { for v in local.nso_routing_ospf : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:router/ospf=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.router_id != null ? { "router-id" = each.value.router_id } : {},
    each.value.log_adjacency_changes == true ? { "log-adjacency-changes" = "" } : {},
    each.value.default_information_originate == true ? { "default-information/originate" = "" } : {},
    each.value.bfd == true ? { "bfd/all-interfaces" = "" } : {},
    each.value.auto_cost_reference_bandwidth != null ? { "auto-cost/reference-bandwidth" = each.value.auto_cost_reference_bandwidth } : {},
    each.value.maximum_paths != null ? { "maximum-paths" = each.value.maximum_paths } : {},
    each.value.default_metric != null ? { "default-metric" = each.value.default_metric } : {},
    each.value.distance != null ? { "distance/weight" = each.value.distance } : {},
    each.value.passive_interface_default == true ? { "passive-interface/default" = "" } : {},
    each.value.graceful_restart == true ? { "graceful-restart-enable/graceful-restart" = "" } : {},
    each.value.rfc1583_compatibility != null ? { "compatible/rfc1583" = each.value.rfc1583_compatibility } : {},
    each.value.default_information_originate_always == true ? { "default-information/originate/always" = "" } : {},
    each.value.timers_throttle_spf_initial != null ? { "timers/throttle/spf/spf-start" = each.value.timers_throttle_spf_initial } : {},
    each.value.timers_throttle_spf_min_hold != null ? { "timers/throttle/spf/spf-hold" = each.value.timers_throttle_spf_min_hold } : {},
    each.value.timers_throttle_spf_max_wait != null ? { "timers/throttle/spf/spf-max-wait" = each.value.timers_throttle_spf_max_wait } : {},
    each.value.timers_throttle_lsa_start != null ? { "timers/throttle/lsa/start-interval" = each.value.timers_throttle_lsa_start } : {},
    each.value.timers_throttle_lsa_hold != null ? { "timers/throttle/lsa/hold-interval" = each.value.timers_throttle_lsa_hold } : {},
    each.value.timers_throttle_lsa_max != null ? { "timers/throttle/lsa/max-interval" = each.value.timers_throttle_lsa_max } : {},
    each.value.nsr == true ? { "nsr" = "" } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.priority != null ? { "priority" = each.value.priority } : {},
  )
}
# ---- END GENERATED resource ospf_iosxe ----

