# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: management.ip_ssh
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_management_ip_ssh = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].ip_ssh, []) : {
        key         = format("%s/ip_ssh/%s", device.name, item.ip_ssh)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        ip_ssh  = item.ip_ssh
        version          = try(item.version,
          null)
        timeout          = try(item.timeout,
          null)
        authentication_retries = try(item.authentication_retries,
          null)
        max_startups     = try(item.max_startups,
          null)
        login_attempts   = try(item.login_attempts,
          null)
        ciphers          = try(item.ciphers,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ip_ssh_nxos ----
resource "nso_device_config" "ip_ssh_nxos" {
  for_each = { for v in local.nso_management_ip_ssh : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ssh"
  delete   = true

  attributes = merge(
    { ssh = tostring(each.value.ip_ssh) },
    each.value.login_attempts != null ? { "login-attempts" = each.value.login_attempts } : {},
    each.value.ciphers != null ? { "ciphers" = each.value.ciphers } : {},
  )
}
# ---- END GENERATED resource ip_ssh_nxos ----
# ---- BEGIN GENERATED resource ip_ssh_iosxe ----
resource "nso_device_config" "ip_ssh_iosxe" {
  for_each = { for v in local.nso_management_ip_ssh : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/ssh"
  delete   = true

  attributes = merge(
    { ssh = tostring(each.value.ip_ssh) },
    each.value.version != null ? { "version" = each.value.version } : {},
    each.value.timeout != null ? { "time-out" = each.value.timeout } : {},
    each.value.authentication_retries != null ? { "authentication-retries" = each.value.authentication_retries } : {},
    each.value.max_startups != null ? { "maxstartups" = each.value.max_startups } : {},
  )
}
# ---- END GENERATED resource ip_ssh_iosxe ----

