# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dns.ip_hosts
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dns_ip_hosts = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dns_ip_hosts, []) : {
        key         = format("%s/ip_host/%s", device.name, item.hostname)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        hostname  = item.hostname
        hostname         = try(item.hostname,
          null)
        address          = try(item.address,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ip_host_nxos ----
resource "nso_device_config" "ip_host_nxos" {
  for_each = { for v in local.nso_dns_ip_hosts : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip/host=${each.value.hostname}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.hostname) },
    each.value.hostname != null ? { "id" = each.value.hostname } : {},
    each.value.address != null ? { "address" = each.value.address } : {},
  )
}
# ---- END GENERATED resource ip_host_nxos ----
# ---- BEGIN GENERATED resource ip_host_iosxe ----
resource "nso_device_config" "ip_host_iosxe" {
  for_each = { for v in local.nso_dns_ip_hosts : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/host/host-list=${each.value.hostname}"
  delete   = true

  attributes = merge(
    { hostname = tostring(each.value.hostname) },
    each.value.hostname != null ? { "hostname" = each.value.hostname } : {},
    each.value.address != null ? { "ip-address1" = each.value.address } : {},
  )
}
# ---- END GENERATED resource ip_host_iosxe ----

