# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: evpn.vni_route_targets
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_evpn_vni_route_targets = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].evpn.vni_route_targets, []) : {
        key         = format("%s/vni_route_target/%s", device.name, item.method)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        method  = item.method
        vni_id           = try(item.vni_id,
          null)
        method           = try(item.method,
          null)
        rt               = try(item.rt,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource vni_route_target_nxos ----
resource "nso_device_config" "vni_route_target_nxos" {
  for_each = { for v in local.nso_evpn_vni_route_targets : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:evpn/vni={vni_id}/route-target=${each.value.method},{rt}"
  delete   = true

  attributes = merge(
    { method = tostring(each.value.method) },
    each.value.vni_id != null ? { "." = each.value.vni_id } : {},
    each.value.method != null ? { "method" = each.value.method } : {},
    each.value.rt != null ? { "rt" = each.value.rt } : {},
  )
}
# ---- END GENERATED resource vni_route_target_nxos ----

