# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: prefix_lists.ipv6_prefix_lists
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_prefix_lists_ipv6_prefix_lists = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].prefix_lists.ipv6_prefix_lists, []) : {
        key         = format("%s/ipv6_prefix_list/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        description      = try(item.description,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ipv6_prefix_list_nxos ----
resource "nso_device_config" "ipv6_prefix_list_nxos" {
  for_each = { for v in local.nso_prefix_lists_ipv6_prefix_lists : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ipv6/prefix-list/prefixes=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
  )
}
# ---- END GENERATED resource ipv6_prefix_list_nxos ----
# ---- BEGIN GENERATED resource ipv6_prefix_list_iosxe ----
resource "nso_device_config" "ipv6_prefix_list_iosxe" {
  for_each = { for v in local.nso_prefix_lists_ipv6_prefix_lists : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ipv6/prefix-list/prefixes=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
  )
}
# ---- END GENERATED resource ipv6_prefix_list_iosxe ----

