# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dhcp.snooping
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dhcp_snooping = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dhcp.snooping, []) : {
        key         = format("%s/snooping/%s", device.name, item.snooping)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        snooping  = item.snooping
        enabled          = try(item.enabled,
          null)
        information_option = try(item.information_option,
          null)
        verify_mac_address = try(item.verify_mac_address,
          null)
        vlans            = try(item.vlans,
          null)
        glean            = try(item.glean,
          null)
        allow_untrusted  = try(item.allow_untrusted,
          null)
        format_snmp_ifindex = try(item.format_snmp_ifindex,
          null)
        format_remote_id_hostname = try(item.format_remote_id_hostname,
          null)
        format_remote_id_string = try(item.format_remote_id_string,
          null)
        database_url     = try(item.database_url,
          null)
        database_write_delay = try(item.database_write_delay,
          null)
        track_host       = try(item.track_host,
          null)
        verify_no_relay_agent_address = try(item.verify_no_relay_agent_address,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource snooping_nxos ----
resource "nso_device_config" "snooping_nxos" {
  for_each = { for v in local.nso_dhcp_snooping : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip/dhcp"
  delete   = true

  attributes = merge(
    { snooping = tostring(each.value.snooping) },
    each.value.enabled == true ? { "snooping" = "" } : {},
    each.value.information_option == true ? { "snooping-config/snooping/information/option" = "" } : {},
    each.value.verify_mac_address != null ? { "snooping-config/snooping/verify/mac-address" = each.value.verify_mac_address } : {},
  )
}
# ---- END GENERATED resource snooping_nxos ----
# ---- BEGIN GENERATED resource snooping_iosxe ----
resource "nso_device_config" "snooping_iosxe" {
  for_each = { for v in local.nso_dhcp_snooping : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/dhcp"
  delete   = true

  attributes = merge(
    { snooping = tostring(each.value.snooping) },
    each.value.enabled == true ? { "snooping-conf/snooping" = "" } : {},
    each.value.information_option != null ? { "snooping/information/option-conf/option" = each.value.information_option } : {},
    each.value.verify_mac_address != null ? { "snooping/verify/mac-address" = each.value.verify_mac_address } : {},
    each.value.vlans != null ? { "snooping/vlan" = each.value.vlans } : {},
    each.value.glean == true ? { "snooping/glean" = "" } : {},
    each.value.allow_untrusted == true ? { "snooping/information/option/allow-untrusted" = "" } : {},
    each.value.format_snmp_ifindex == true ? { "snooping/information/option/format/snmp-ifindex" = "" } : {},
    each.value.format_remote_id_hostname == true ? { "snooping/information/option/format/remote-id/remote-id-choice/hostname/hostname" = "" } : {},
    each.value.format_remote_id_string != null ? { "snooping/information/option/format/remote-id/remote-id-choice/string/string" = each.value.format_remote_id_string } : {},
    each.value.database_url != null ? { "snooping/database/url" = each.value.database_url } : {},
    each.value.database_write_delay != null ? { "snooping/database/write-delay" = each.value.database_write_delay } : {},
    each.value.track_host == true ? { "snooping/track/host" = "" } : {},
    each.value.verify_no_relay_agent_address == true ? { "snooping/verify/no-relay-agent-address" = "" } : {},
  )
}
# ---- END GENERATED resource snooping_iosxe ----

