# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:d003c4bcca05...)
# Feature: interfaces.loopbacks
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_interfaces_loopbacks = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].interfaces.loopbacks, []) : {
        key         = format("%s/loopback/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        description      = try(item.description,
          null)
        shutdown         = try(item.shutdown,
          null)
        vrf              = try(item.vrf,
          null)
        ipv4_address     = try(item.ipv4_address,
          null)
        ipv4_mask        = try(item.ipv4_mask,
          null)
        ip_proxy_arp     = try(item.ip_proxy_arp,
          null)
        ip_redirects     = try(item.ip_redirects,
          null)
        ip_unreachables  = try(item.ip_unreachables,
          null)
        logging_event_link_status = try(item.logging_event_link_status,
          null)
        arp_timeout      = try(item.arp_timeout,
          null)
        bandwidth        = try(item.bandwidth,
          null)
        delay            = try(item.delay,
          null)
        mtu              = try(item.mtu,
          null)
        load_interval    = try(item.load_interval,
          null)
        mac_address      = try(item.mac_address,
          null)
        ip_tcp_adjust_mss = try(item.ip_tcp_adjust_mss,
          null)
        service_policy_input = try(item.service_policy_input,
          null)
        service_policy_output = try(item.service_policy_output,
          null)
        ip_directed_broadcast = try(item.ip_directed_broadcast,
          null)
        ip_forward       = try(item.ip_forward,
          null)
        lldp_transmit    = try(item.lldp_transmit,
          null)
        lldp_receive     = try(item.lldp_receive,
          null)
        bfd_template     = try(item.bfd_template,
          null)
        keepalive        = try(item.keepalive,
          null)
        snmp_trap_link_status = try(item.snmp_trap_link_status,
          null)
        ip_ospf_cost     = try(item.ip_ospf_cost,
          null)
        ip_ospf_network_type = try(item.ip_ospf_network_type,
          null)
        ip_ospf_priority = try(item.ip_ospf_priority,
          null)
        ip_ospf_hello_interval = try(item.ip_ospf_hello_interval,
          null)
        ip_ospf_dead_interval = try(item.ip_ospf_dead_interval,
          null)
        ip_ospf_retransmit_interval = try(item.ip_ospf_retransmit_interval,
          null)
        ip_ospf_transmit_delay = try(item.ip_ospf_transmit_delay,
          null)
        ip_ospf_mtu_ignore = try(item.ip_ospf_mtu_ignore,
          null)
        ip_ospf_shutdown = try(item.ip_ospf_shutdown,
          null)
        ip_ospf_passive_interface = try(item.ip_ospf_passive_interface,
          null)
        ip_router_ospf_name = try(item.ip_router_ospf_name,
          null)
        ip_router_ospf_area = try(item.ip_router_ospf_area,
          null)
        ip_policy_route_map = try(item.ip_policy_route_map,
          null)
        ip_nat           = try(item.ip_nat,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource loopback_nxos ----
resource "nso_device_config" "loopback_nxos" {
  for_each = { for v in local.nso_interfaces_loopbacks : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:interface/loopback=${each.value.id}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.id) },
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.vrf != null ? { "vrf/member" = each.value.vrf } : {},
    each.value.ipv4_address != null ? { "ip/static/address/ipaddr" = each.value.ipv4_address } : {},
    each.value.ip_proxy_arp == true ? { "ip/proxy-arp" = "" } : {},
    each.value.ip_redirects != null ? { "ip/redirects" = each.value.ip_redirects } : {},
    each.value.ip_unreachables == true ? { "ip/unreachables" = "" } : {},
    each.value.logging_event_link_status != null ? { "logging/event/port/linkstatus" = each.value.logging_event_link_status } : {},
    each.value.arp_timeout != null ? { "ip/arp/timeout" = each.value.arp_timeout } : {},
    each.value.ip_directed_broadcast == true ? { "ip/directed-broadcast" = "" } : {},
    each.value.ip_forward == true ? { "ip/forward" = "" } : {},
    each.value.ip_ospf_cost != null ? { "ip/ospf/cost" = each.value.ip_ospf_cost } : {},
    each.value.ip_ospf_network_type != null ? { "ip/ospf/network" = each.value.ip_ospf_network_type } : {},
    each.value.ip_ospf_priority != null ? { "ip/ospf/priority" = each.value.ip_ospf_priority } : {},
    each.value.ip_ospf_hello_interval != null ? { "ip/ospf/hello-interval" = each.value.ip_ospf_hello_interval } : {},
    each.value.ip_ospf_dead_interval != null ? { "ip/ospf/dead-interval" = each.value.ip_ospf_dead_interval } : {},
    each.value.ip_ospf_retransmit_interval != null ? { "ip/ospf/retransmit-interval" = each.value.ip_ospf_retransmit_interval } : {},
    each.value.ip_ospf_transmit_delay != null ? { "ip/ospf/transmit-delay" = each.value.ip_ospf_transmit_delay } : {},
    each.value.ip_ospf_mtu_ignore == true ? { "ip/ospf/mtu-ignore" = "" } : {},
    each.value.ip_ospf_shutdown == true ? { "ip/ospf/shutdown" = "" } : {},
    each.value.ip_ospf_passive_interface != null ? { "ip/ospf/passive-interface" = each.value.ip_ospf_passive_interface } : {},
    each.value.ip_router_ospf_name != null ? { "ip/router/ospf/name" = each.value.ip_router_ospf_name } : {},
    each.value.ip_router_ospf_area != null ? { "ip/router/ospf/area" = each.value.ip_router_ospf_area } : {},
    each.value.ip_policy_route_map != null ? { "ip/policy/route-map" = each.value.ip_policy_route_map } : {},
    each.value.ip_nat != null ? { "ip/nat" = each.value.ip_nat } : {},
  )
}
# ---- END GENERATED resource loopback_nxos ----
# ---- BEGIN GENERATED resource loopback_iosxe ----
resource "nso_device_config" "loopback_iosxe" {
  for_each = { for v in local.nso_interfaces_loopbacks : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:interface/Loopback=${each.value.id}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.id) },
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.vrf != null ? { "vrf/vrf/forwarding" = each.value.vrf } : {},
    each.value.ipv4_address != null ? { "ip/address/address/fixed-case/primary/address" = each.value.ipv4_address } : {},
    each.value.ipv4_mask != null ? { "ip/address/address/fixed-case/primary/mask" = each.value.ipv4_mask } : {},
    each.value.ip_proxy_arp != null ? { "ip/proxy-arp" = each.value.ip_proxy_arp } : {},
    each.value.ip_redirects != null ? { "ip/redirects" = each.value.ip_redirects } : {},
    each.value.ip_unreachables != null ? { "ip/unreachables" = each.value.ip_unreachables } : {},
    each.value.logging_event_link_status != null ? { "logging/event/link-status" = each.value.logging_event_link_status } : {},
    each.value.arp_timeout != null ? { "arp/timeout" = each.value.arp_timeout } : {},
    each.value.bandwidth != null ? { "bandwidth/kilobits" = each.value.bandwidth } : {},
    each.value.delay != null ? { "delay" = each.value.delay } : {},
    each.value.mtu != null ? { "mtu" = each.value.mtu } : {},
    each.value.load_interval != null ? { "load-interval" = each.value.load_interval } : {},
    each.value.mac_address != null ? { "mac-address" = each.value.mac_address } : {},
    each.value.ip_tcp_adjust_mss != null ? { "ip/tcp/adjust-mss" = each.value.ip_tcp_adjust_mss } : {},
    each.value.service_policy_input != null ? { "service-policy/input" = each.value.service_policy_input } : {},
    each.value.service_policy_output != null ? { "service-policy/output" = each.value.service_policy_output } : {},
    each.value.lldp_transmit != null ? { "lldp/transmit" = each.value.lldp_transmit } : {},
    each.value.lldp_receive != null ? { "lldp/receive" = each.value.lldp_receive } : {},
    each.value.bfd_template != null ? { "bfd/template" = each.value.bfd_template } : {},
    each.value.keepalive != null ? { "keepalive" = each.value.keepalive } : {},
    each.value.snmp_trap_link_status != null ? { "snmp/trap/link-status" = each.value.snmp_trap_link_status } : {},
    each.value.ip_ospf_cost != null ? { "ip/ospf/cost" = each.value.ip_ospf_cost } : {},
    each.value.ip_ospf_network_type != null ? { "ip/ospf/network" = each.value.ip_ospf_network_type } : {},
    each.value.ip_ospf_priority != null ? { "ip/ospf/priority" = each.value.ip_ospf_priority } : {},
    each.value.ip_ospf_hello_interval != null ? { "ip/ospf/hello-interval" = each.value.ip_ospf_hello_interval } : {},
    each.value.ip_ospf_dead_interval != null ? { "ip/ospf/dead-interval/seconds" = each.value.ip_ospf_dead_interval } : {},
    each.value.ip_ospf_retransmit_interval != null ? { "ip/ospf/retransmit-interval" = each.value.ip_ospf_retransmit_interval } : {},
    each.value.ip_ospf_transmit_delay != null ? { "ip/ospf/transmit-delay" = each.value.ip_ospf_transmit_delay } : {},
    each.value.ip_ospf_mtu_ignore == true ? { "ip/ospf/mtu-ignore" = "" } : {},
    each.value.ip_ospf_shutdown == true ? { "ip/ospf/shutdown" = "" } : {},
    each.value.ip_policy_route_map != null ? { "ip/policy/route-map" = each.value.ip_policy_route_map } : {},
  )
}
# ---- END GENERATED resource loopback_iosxe ----

