# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: acls.ipv6_global
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_acls_ipv6_global = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].acls.ipv6_global, []) : {
        key         = format("%s/ipv6_global/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        match_local_traffic = try(item.match_local_traffic,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ipv6_global_nxos ----
resource "nso_device_config" "ipv6_global_nxos" {
  for_each = { for v in local.nso_acls_ipv6_global : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ipv6/access-list"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "." = each.value.id } : {},
    each.value.match_local_traffic == true ? { "match-local-traffic" = "" } : {},
  )
}
# ---- END GENERATED resource ipv6_global_nxos ----

