# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: fhrp.hsrp_track
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_fhrp_hsrp_track = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].fhrp.hsrp_track, []) : {
        key         = format("%s/hsrp_track/%s", device.name, item.track_id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        track_id  = item.track_id
        decrement        = try(item.decrement,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource hsrp_track_nxos ----
resource "nso_device_config" "hsrp_track_nxos" {
  for_each = { for v in local.nso_fhrp_hsrp_track : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:interface/Vlan={interface_id}/hsrp/hsrp-list={group_id},{address_family}/track=${each.value.track_id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.track_id) },
    each.value.decrement != null ? { "decrement" = each.value.decrement } : {},
  )
}
# ---- END GENERATED resource hsrp_track_nxos ----
# ---- BEGIN GENERATED resource hsrp_track_iosxe ----
resource "nso_device_config" "hsrp_track_iosxe" {
  for_each = { for v in local.nso_fhrp_hsrp_track : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:interface/Vlan={interface_id}/standby/standby-list={group_id}/track=${each.value.track_id}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.track_id) },
    each.value.decrement != null ? { "options/decrement" = each.value.decrement } : {},
  )
}
# ---- END GENERATED resource hsrp_track_iosxe ----

