# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: qos.mls_aggregate_policers
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_qos_mls_aggregate_policers = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].qos.mls_aggregate_policers, []) : {
        key         = format("%s/mls_aggregate_policer/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        target_bit_rate  = try(item.target_bit_rate,
          null)
        burst_normal     = try(item.burst_normal,
          null)
        burst_max        = try(item.burst_max,
          null)
        pir              = try(item.pir,
          null)
        exceed_action    = try(item.exceed_action,
          null)
        violate_action   = try(item.violate_action,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource mls_aggregate_policer_iosxe ----
resource "nso_device_config" "mls_aggregate_policer_iosxe" {
  for_each = { for v in local.nso_qos_mls_aggregate_policers : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:mls/qos/aggregate-policer=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.target_bit_rate != null ? { "target-bit-rate" = each.value.target_bit_rate } : {},
    each.value.burst_normal != null ? { "burst-normal" = each.value.burst_normal } : {},
    each.value.burst_max != null ? { "burst-max" = each.value.burst_max } : {},
    each.value.pir != null ? { "pir" = each.value.pir } : {},
    each.value.exceed_action != null ? { "exceed-action" = each.value.exceed_action } : {},
    each.value.violate_action != null ? { "violate-action" = each.value.violate_action } : {},
  )
}
# ---- END GENERATED resource mls_aggregate_policer_iosxe ----

