# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dhcp.global
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dhcp_global = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dhcp.global, []) : {
        key         = format("%s/global/%s", device.name, item.global)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        global  = item.global
        smart_relay      = try(item.smart_relay,
          null)
        conflict_logging = try(item.conflict_logging,
          null)
        bootp_ignore     = try(item.bootp_ignore,
          null)
        binding_cleanup_interval = try(item.binding_cleanup_interval,
          null)
        use_vrf_connected = try(item.use_vrf_connected,
          null)
        use_vrf_remote   = try(item.use_vrf_remote,
          null)
        compatibility_suboption_link_selection = try(item.compatibility_suboption_link_selection,
          null)
        packet_strict_validation = try(item.packet_strict_validation,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource global_nxos ----
resource "nso_device_config" "global_nxos" {
  for_each = { for v in local.nso_dhcp_global : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip/dhcp"
  delete   = true

  attributes = merge(
    { global = tostring(each.value.global) },
    each.value.smart_relay == true ? { "smart-relay/global" = "" } : {},
    each.value.packet_strict_validation == true ? { "packet/strict-validation" = "" } : {},
  )
}
# ---- END GENERATED resource global_nxos ----
# ---- BEGIN GENERATED resource global_iosxe ----
resource "nso_device_config" "global_iosxe" {
  for_each = { for v in local.nso_dhcp_global : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/dhcp"
  delete   = true

  attributes = merge(
    { global = tostring(each.value.global) },
    each.value.smart_relay == true ? { "smart-relay" = "" } : {},
    each.value.conflict_logging != null ? { "conflict/logging" = each.value.conflict_logging } : {},
    each.value.bootp_ignore == true ? { "bootp/ignore" = "" } : {},
    each.value.binding_cleanup_interval != null ? { "binding/cleanup/interval" = each.value.binding_cleanup_interval } : {},
    each.value.use_vrf_connected != null ? { "use/vrf/connected" = each.value.use_vrf_connected } : {},
    each.value.use_vrf_remote == true ? { "use/vrf/remote" = "" } : {},
    each.value.compatibility_suboption_link_selection != null ? { "compatibility/suboption/link-selection" = each.value.compatibility_suboption_link_selection } : {},
  )
}
# ---- END GENERATED resource global_iosxe ----

