# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: discovery.lldp
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_discovery_lldp = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].lldp, []) : {
        key         = format("%s/lldp/%s", device.name, item.lldp)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        lldp  = item.lldp
        run              = try(item.run,
          null)
        holdtime         = try(item.holdtime,
          null)
        timer            = try(item.timer,
          null)
        reinit           = try(item.reinit,
          null)
        portid_subtype   = try(item.portid_subtype,
          null)
        tlv_select_dcbxp = try(item.tlv_select_dcbxp,
          null)
        tlv_select_port_description = try(item.tlv_select_port_description,
          null)
        tlv_select_port_vlan = try(item.tlv_select_port_vlan,
          null)
        tlv_select_power_management = try(item.tlv_select_power_management,
          null)
        tlv_select_four_wire_power_management = try(item.tlv_select_four_wire_power_management,
          null)
        tlv_select_system_capabilities = try(item.tlv_select_system_capabilities,
          null)
        tlv_select_system_description = try(item.tlv_select_system_description,
          null)
        tlv_select_system_name = try(item.tlv_select_system_name,
          null)
        tlv_select_management_address_v4 = try(item.tlv_select_management_address_v4,
          null)
        tlv_select_management_address_v6 = try(item.tlv_select_management_address_v6,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource lldp_nxos ----
resource "nso_device_config" "lldp_nxos" {
  for_each = { for v in local.nso_discovery_lldp : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:lldp"
  delete   = true

  attributes = merge(
    { lldp = tostring(each.value.lldp) },
    each.value.holdtime != null ? { "holdtime" = each.value.holdtime } : {},
    each.value.timer != null ? { "timer" = each.value.timer } : {},
    each.value.reinit != null ? { "reinit" = each.value.reinit } : {},
    each.value.portid_subtype != null ? { "portid-subtype" = each.value.portid_subtype } : {},
    each.value.tlv_select_dcbxp != null ? { "tlv-select/dcbxp" = each.value.tlv_select_dcbxp } : {},
    each.value.tlv_select_port_description != null ? { "tlv-select/port-description" = each.value.tlv_select_port_description } : {},
    each.value.tlv_select_port_vlan != null ? { "tlv-select/port-vlan" = each.value.tlv_select_port_vlan } : {},
    each.value.tlv_select_power_management != null ? { "tlv-select/power-management" = each.value.tlv_select_power_management } : {},
    each.value.tlv_select_four_wire_power_management != null ? { "tlv-select/four-wire-power-management" = each.value.tlv_select_four_wire_power_management } : {},
    each.value.tlv_select_system_capabilities != null ? { "tlv-select/system-capabilities" = each.value.tlv_select_system_capabilities } : {},
    each.value.tlv_select_system_description != null ? { "tlv-select/system-description" = each.value.tlv_select_system_description } : {},
    each.value.tlv_select_system_name != null ? { "tlv-select/system-name" = each.value.tlv_select_system_name } : {},
    each.value.tlv_select_management_address_v4 != null ? { "tlv-select/management-address/v4" = each.value.tlv_select_management_address_v4 } : {},
    each.value.tlv_select_management_address_v6 != null ? { "tlv-select/management-address/v6" = each.value.tlv_select_management_address_v6 } : {},
  )
}
# ---- END GENERATED resource lldp_nxos ----
# ---- BEGIN GENERATED resource lldp_iosxe ----
resource "nso_device_config" "lldp_iosxe" {
  for_each = { for v in local.nso_discovery_lldp : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:lldp"
  delete   = true

  attributes = merge(
    { lldp = tostring(each.value.lldp) },
    each.value.run == true ? { "run" = "" } : {},
    each.value.holdtime != null ? { "holdtime" = each.value.holdtime } : {},
    each.value.timer != null ? { "timer" = each.value.timer } : {},
    each.value.reinit != null ? { "reinit" = each.value.reinit } : {},
  )
}
# ---- END GENERATED resource lldp_iosxe ----

