# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.authorization_commands
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_authorization_commands = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_authorization_commands, []) : {
        key         = format("%s/authorization_command/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        level            = try(item.level,
          null)
        name             = try(item.name,
          null)
        group            = try(item.group,
          null)
        local            = try(item.local,
          null)
        none             = try(item.none,
          null)
        if_authenticated = try(item.if_authenticated,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource authorization_command_iosxe ----
resource "nso_device_config" "authorization_command_iosxe" {
  for_each = { for v in local.nso_aaa_authorization_commands : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:aaa/authorization/commands={level},${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.level != null ? { "level" = each.value.level } : {},
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.group != null ? { "group" = each.value.group } : {},
    each.value.local == true ? { "local" = "" } : {},
    each.value.none == true ? { "none" = "" } : {},
    each.value.if_authenticated == true ? { "if-authenticated" = "" } : {},
  )
}
# ---- END GENERATED resource authorization_command_iosxe ----

