# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: routing.bgp
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_routing_bgp = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].routing.bgp, []) : {
        key         = format("%s/bgp/%s", device.name, item.asn)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        asn  = item.asn
        router_id        = try(item.router_id,
          null)
        log_neighbor_changes = try(item.log_neighbor_changes,
          null)
        graceful_restart = try(item.graceful_restart,
          null)
        graceful_restart_restart_time = try(item.graceful_restart_restart_time,
          null)
        graceful_restart_stalepath_time = try(item.graceful_restart_stalepath_time,
          null)
        timers_keepalive = try(item.timers_keepalive,
          null)
        timers_holdtime  = try(item.timers_holdtime,
          null)
        bestpath_always_compare_med = try(item.bestpath_always_compare_med,
          null)
        bestpath_compare_routerid = try(item.bestpath_compare_routerid,
          null)
        bestpath_as_path_multipath_relax = try(item.bestpath_as_path_multipath_relax,
          null)
        bestpath_med_confed = try(item.bestpath_med_confed,
          null)
        bestpath_med_missing_as_worst = try(item.bestpath_med_missing_as_worst,
          null)
        bestpath_cost_community_ignore = try(item.bestpath_cost_community_ignore,
          null)
        cluster_id       = try(item.cluster_id,
          null)
        enforce_first_as = try(item.enforce_first_as,
          null)
        bestpath_as_path_ignore = try(item.bestpath_as_path_ignore,
          null)
        bestpath_med_non_deterministic = try(item.bestpath_med_non_deterministic,
          null)
        bestpath_compare_neighborid = try(item.bestpath_compare_neighborid,
          null)
        suppress_fib_pending = try(item.suppress_fib_pending,
          null)
        neighbor_down_fib_accelerate = try(item.neighbor_down_fib_accelerate,
          null)
        synchronization  = try(item.synchronization,
          null)
        auto_summary     = try(item.auto_summary,
          null)
        deterministic_med = try(item.deterministic_med,
          null)
        fast_external_fallover = try(item.fast_external_fallover,
          null)
        default_ipv4_unicast = try(item.default_ipv4_unicast,
          null)
        default_local_preference = try(item.default_local_preference,
          null)
        client_to_client_reflection = try(item.client_to_client_reflection,
          null)
        maxas_limit      = try(item.maxas_limit,
          null)
        distance_ebgp    = try(item.distance_ebgp,
          null)
        distance_ibgp    = try(item.distance_ibgp,
          null)
        distance_local   = try(item.distance_local,
          null)
        maximum_paths    = try(item.maximum_paths,
          null)
        default_information_originate = try(item.default_information_originate,
          null)
        default_metric   = try(item.default_metric,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource bgp_nxos ----
resource "nso_device_config" "bgp_nxos" {
  for_each = { for v in local.nso_routing_bgp : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:router/bgp=${each.value.asn}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.asn) },
    each.value.router_id != null ? { "router-id" = each.value.router_id } : {},
    each.value.log_neighbor_changes == true ? { "log-neighbor-changes" = "" } : {},
    each.value.graceful_restart != null ? { "graceful-restart" = each.value.graceful_restart } : {},
    each.value.graceful_restart_restart_time != null ? { "graceful-restart-config/graceful-restart/restart-time" = each.value.graceful_restart_restart_time } : {},
    each.value.graceful_restart_stalepath_time != null ? { "graceful-restart-config/graceful-restart/stalepath-time" = each.value.graceful_restart_stalepath_time } : {},
    each.value.timers_keepalive != null ? { "timers/bgp/keepalive" = each.value.timers_keepalive } : {},
    each.value.timers_holdtime != null ? { "timers/bgp/holdtime" = each.value.timers_holdtime } : {},
    each.value.bestpath_always_compare_med == true ? { "bestpath/always-compare-med" = "" } : {},
    each.value.bestpath_compare_routerid == true ? { "bestpath/compare-routerid" = "" } : {},
    each.value.bestpath_as_path_multipath_relax == true ? { "bestpath/as-path/multipath-relax" = "" } : {},
    each.value.bestpath_med_confed == true ? { "bestpath/med/confed" = "" } : {},
    each.value.bestpath_med_missing_as_worst == true ? { "bestpath/med/missing-as-worst" = "" } : {},
    each.value.bestpath_cost_community_ignore == true ? { "bestpath/cost-community/ignore" = "" } : {},
    each.value.cluster_id != null ? { "cluster-id" = each.value.cluster_id } : {},
    each.value.enforce_first_as != null ? { "enforce-first-as" = each.value.enforce_first_as } : {},
    each.value.bestpath_as_path_ignore == true ? { "bestpath/as-path/ignore" = "" } : {},
    each.value.bestpath_med_non_deterministic == true ? { "bestpath/med/non-deterministic" = "" } : {},
    each.value.bestpath_compare_neighborid == true ? { "bestpath/compare-neighborid" = "" } : {},
    each.value.suppress_fib_pending == true ? { "suppress-fib-pending" = "" } : {},
    each.value.neighbor_down_fib_accelerate == true ? { "neighbor-down/fib-accelerate" = "" } : {},
  )
}
# ---- END GENERATED resource bgp_nxos ----
# ---- BEGIN GENERATED resource bgp_iosxe ----
resource "nso_device_config" "bgp_iosxe" {
  for_each = { for v in local.nso_routing_bgp : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:router/bgp=${each.value.asn}"
  delete   = true

  attributes = merge(
    { as-no = tostring(each.value.asn) },
    each.value.router_id != null ? { "bgp/router-id" = each.value.router_id } : {},
    each.value.log_neighbor_changes != null ? { "bgp/log-neighbor-changes" = each.value.log_neighbor_changes } : {},
    each.value.graceful_restart == true ? { "bgp/graceful-restart" = "" } : {},
    each.value.graceful_restart_restart_time != null ? { "bgp/graceful-restart-conf/graceful-restart/restart-time" = each.value.graceful_restart_restart_time } : {},
    each.value.graceful_restart_stalepath_time != null ? { "bgp/graceful-restart-conf/graceful-restart/stalepath-time" = each.value.graceful_restart_stalepath_time } : {},
    each.value.timers_keepalive != null ? { "timers/bgp/keepalive" = each.value.timers_keepalive } : {},
    each.value.timers_holdtime != null ? { "timers/bgp/holdtime" = each.value.timers_holdtime } : {},
    each.value.bestpath_always_compare_med == true ? { "bgp/always-compare-med" = "" } : {},
    each.value.bestpath_compare_routerid == true ? { "bgp/bestpath/compare-routerid" = "" } : {},
    each.value.bestpath_as_path_multipath_relax == true ? { "bgp/bestpath/as-path/multipath-relax" = "" } : {},
    each.value.bestpath_med_confed == true ? { "bgp/bestpath/med/confed" = "" } : {},
    each.value.bestpath_med_missing_as_worst == true ? { "bgp/bestpath/med/missing-as-worst" = "" } : {},
    each.value.bestpath_cost_community_ignore == true ? { "bgp/bestpath/cost-community/ignore" = "" } : {},
    each.value.cluster_id != null ? { "bgp/cluster-id" = each.value.cluster_id } : {},
    each.value.enforce_first_as != null ? { "bgp/enforce-first-as" = each.value.enforce_first_as } : {},
    each.value.synchronization == true ? { "synchronization" = "" } : {},
    each.value.auto_summary != null ? { "auto-summary" = each.value.auto_summary } : {},
    each.value.deterministic_med == true ? { "bgp/deterministic-med" = "" } : {},
    each.value.fast_external_fallover != null ? { "bgp/fast-external-fallover" = each.value.fast_external_fallover } : {},
    each.value.default_ipv4_unicast != null ? { "bgp/default/ipv4-unicast" = each.value.default_ipv4_unicast } : {},
    each.value.default_local_preference != null ? { "bgp/default/local-preference" = each.value.default_local_preference } : {},
    each.value.client_to_client_reflection != null ? { "bgp/client-to-client/reflection" = each.value.client_to_client_reflection } : {},
    each.value.maxas_limit != null ? { "bgp/maxas-limit" = each.value.maxas_limit } : {},
    each.value.distance_ebgp != null ? { "distance/bgp/extern-as" = each.value.distance_ebgp } : {},
    each.value.distance_ibgp != null ? { "distance/bgp/internal-as" = each.value.distance_ibgp } : {},
    each.value.distance_local != null ? { "distance/bgp/local" = each.value.distance_local } : {},
    each.value.maximum_paths != null ? { "maximum-paths/paths/number-of-paths" = each.value.maximum_paths } : {},
    each.value.default_information_originate == true ? { "default-information/originate" = "" } : {},
    each.value.default_metric != null ? { "default-metric" = each.value.default_metric } : {},
  )
}
# ---- END GENERATED resource bgp_iosxe ----

