# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: vxlan.nve_vnis
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_vxlan_nve_vnis = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].vxlan.nve_vnis, []) : {
        key         = format("%s/nve_vni/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        nve_id           = try(item.nve_id,
          null)
        associate_vrf    = try(item.associate_vrf,
          null)
        vrf              = try(item.vrf,
          null)
        mcast_group      = try(item.mcast_group,
          null)
        suppress_arp     = try(item.suppress_arp,
          null)
        suppress_unknown_unicast = try(item.suppress_unknown_unicast,
          null)
        ingress_replication_bgp = try(item.ingress_replication_bgp,
          null)
        host_reachability_protocol = try(item.host_reachability_protocol,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource nve_vni_nxos ----
resource "nso_device_config" "nve_vni_nxos" {
  for_each = { for v in local.nso_vxlan_nve_vnis : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:interface/nve={nve_id}/member/vni=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.nve_id != null ? { "." = each.value.nve_id } : {},
    each.value.associate_vrf == true ? { "associate-vrf" = "" } : {},
    each.value.vrf != null ? { "vrf" = each.value.vrf } : {},
    each.value.mcast_group != null ? { "mcast-group" = each.value.mcast_group } : {},
    each.value.suppress_arp == true ? { "suppress-arp" = "" } : {},
    each.value.suppress_unknown_unicast == true ? { "suppress-unknown-unicast" = "" } : {},
    each.value.ingress_replication_bgp == true ? { "ingress-replication/protocol/bgp" = "" } : {},
    each.value.host_reachability_protocol != null ? { "host-reachability/protocol" = each.value.host_reachability_protocol } : {},
  )
}
# ---- END GENERATED resource nve_vni_nxos ----
# ---- BEGIN GENERATED resource nve_vni_iosxe ----
resource "nso_device_config" "nve_vni_iosxe" {
  for_each = { for v in local.nso_vxlan_nve_vnis : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:interface/nve={nve_id}/member/vni=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.nve_id != null ? { "." = each.value.nve_id } : {},
    each.value.mcast_group != null ? { "mcast-group" = each.value.mcast_group } : {},
    each.value.ingress_replication_bgp == true ? { "ingress-replication/local-routing/local-routing" = "" } : {},
  )
}
# ---- END GENERATED resource nve_vni_iosxe ----

