# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: qos.mls_qos
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_qos_mls_qos = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].qos.mls_qos, []) : {
        key         = format("%s/mls_qo/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        enabled          = try(item.enabled,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource mls_qo_iosxe ----
resource "nso_device_config" "mls_qo_iosxe" {
  for_each = { for v in local.nso_qos_mls_qos : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:mls/mls-qos-conf"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "." = each.value.id } : {},
    each.value.enabled == true ? { "qos" = "" } : {},
  )
}
# ---- END GENERATED resource mls_qo_iosxe ----

