# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: vrfs.definition
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_vrfs_definition = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].vrfs.definition, []) : {
        key         = format("%s/definition/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        description      = try(item.description,
          null)
        rd               = try(item.rd,
          null)
        vni              = try(item.vni,
          null)
        vni_l3           = try(item.vni_l3,
          null)
        vpn_id           = try(item.vpn_id,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource definition_nxos ----
resource "nso_device_config" "definition_nxos" {
  for_each = { for v in local.nso_vrfs_definition : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:vrf/context={id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.rd != null ? { "rd" = each.value.rd } : {},
    each.value.vni != null ? { "vni/id" = each.value.vni } : {},
    each.value.vni_l3 == true ? { "vni/l3" = "" } : {},
  )
}
# ---- END GENERATED resource definition_nxos ----
# ---- BEGIN GENERATED resource definition_iosxe ----
resource "nso_device_config" "definition_iosxe" {
  for_each = { for v in local.nso_vrfs_definition : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:vrf/definition=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.rd != null ? { "rd" = each.value.rd } : {},
    each.value.vpn_id != null ? { "vpn/id" = each.value.vpn_id } : {},
  )
}
# ---- END GENERATED resource definition_iosxe ----

