# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.ntp
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_ntp = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].ntp, []) : {
        key         = format("%s/ntp/%s", device.name, item.ntp)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        ntp  = item.ntp
        authenticate     = try(item.authenticate,
          null)
        logging          = try(item.logging,
          null)
        source_interface = try(item.source_interface,
          null)
        master           = try(item.master,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ntp_nxos ----
resource "nso_device_config" "ntp_nxos" {
  for_each = { for v in local.nso_system_ntp : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ntp"
  delete   = true

  attributes = merge(
    { ntp = tostring(each.value.ntp) },
    each.value.authenticate == true ? { "authenticate" = "" } : {},
    each.value.logging == true ? { "logging" = "" } : {},
    each.value.source_interface != null ? { "source-interface" = each.value.source_interface } : {},
    each.value.master != null ? { "master" = each.value.master } : {},
  )
}
# ---- END GENERATED resource ntp_nxos ----
# ---- BEGIN GENERATED resource ntp_iosxe ----
resource "nso_device_config" "ntp_iosxe" {
  for_each = { for v in local.nso_system_ntp : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ntp"
  delete   = true

  attributes = merge(
    { ntp = tostring(each.value.ntp) },
    each.value.authenticate == true ? { "authenticate" = "" } : {},
    each.value.logging == true ? { "logging" = "" } : {},
  )
}
# ---- END GENERATED resource ntp_iosxe ----

