# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: acls.ipv4_extended
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_acls_ipv4_extended = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].acls.ipv4_extended, []) : {
        key         = format("%s/ipv4_extended/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ipv4_extended_iosxe ----
resource "nso_device_config" "ipv4_extended_iosxe" {
  for_each = { for v in local.nso_acls_ipv4_extended : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/access-list/extended/ext-named-acl=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource ipv4_extended_iosxe ----

