# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.usernames
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_usernames = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_usernames, []) : {
        key         = format("%s/username/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        privilege        = try(item.privilege,
          null)
        role             = try(item.role,
          null)
        secret_type      = try(item.secret_type,
          null)
        secret           = try(item.secret,
          null)
        password_encryption = try(item.password_encryption,
          null)
        password         = try(item.password,
          null)
        expire           = try(item.expire,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource username_nxos ----
resource "nso_device_config" "username_nxos" {
  for_each = { for v in local.nso_aaa_usernames : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:username=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.role != null ? { "role" = each.value.role } : {},
    each.value.password_encryption != null ? { "password/encryption" = each.value.password_encryption } : {},
    each.value.password != null ? { "password/password" = each.value.password } : {},
    each.value.expire != null ? { "expire" = each.value.expire } : {},
  )
}
# ---- END GENERATED resource username_nxos ----
# ---- BEGIN GENERATED resource username_iosxe ----
resource "nso_device_config" "username_iosxe" {
  for_each = { for v in local.nso_aaa_usernames : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:username=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.privilege != null ? { "privilege" = each.value.privilege } : {},
    each.value.secret_type != null ? { "secret/type" = each.value.secret_type } : {},
    each.value.secret != null ? { "secret/secret" = each.value.secret } : {},
  )
}
# ---- END GENERATED resource username_iosxe ----

