# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dns.name_servers
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dns_name_servers = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dns_name_servers, []) : {
        key         = format("%s/name_server/%s", device.name, item.address)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        address  = item.address
        address          = try(item.address,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource name_server_nxos ----
resource "nso_device_config" "name_server_nxos" {
  for_each = { for v in local.nso_dns_name_servers : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip/name-server"
  delete   = true

  attributes = merge(
    { servers = tostring(each.value.address) },
    each.value.address != null ? { "servers" = each.value.address } : {},
  )
}
# ---- END GENERATED resource name_server_nxos ----
# ---- BEGIN GENERATED resource name_server_iosxe ----
resource "nso_device_config" "name_server_iosxe" {
  for_each = { for v in local.nso_dns_name_servers : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/name-server/name-server-list=${each.value.address}"
  delete   = true

  attributes = merge(
    { address = tostring(each.value.address) },
    each.value.address != null ? { "address" = each.value.address } : {},
  )
}
# ---- END GENERATED resource name_server_iosxe ----

