# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.spanning_tree_vlan
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_spanning_tree_vlan = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].spanning_tree_vlan, []) : {
        key         = format("%s/spanning_tree_vlan/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        priority         = try(item.priority,
          null)
        hello_time       = try(item.hello_time,
          null)
        forward_time     = try(item.forward_time,
          null)
        max_age          = try(item.max_age,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource spanning_tree_vlan_nxos ----
resource "nso_device_config" "spanning_tree_vlan_nxos" {
  for_each = { for v in local.nso_system_spanning_tree_vlan : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:spanning-tree/vlan/vlan-list=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.priority != null ? { "priority" = each.value.priority } : {},
    each.value.hello_time != null ? { "hello-time" = each.value.hello_time } : {},
    each.value.forward_time != null ? { "forward-time" = each.value.forward_time } : {},
    each.value.max_age != null ? { "max-age" = each.value.max_age } : {},
  )
}
# ---- END GENERATED resource spanning_tree_vlan_nxos ----
# ---- BEGIN GENERATED resource spanning_tree_vlan_iosxe ----
resource "nso_device_config" "spanning_tree_vlan_iosxe" {
  for_each = { for v in local.nso_system_spanning_tree_vlan : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:spanning-tree/vlan/vlan-list=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.priority != null ? { "priority" = each.value.priority } : {},
    each.value.hello_time != null ? { "hello-time" = each.value.hello_time } : {},
    each.value.forward_time != null ? { "forward-time" = each.value.forward_time } : {},
    each.value.max_age != null ? { "max-age" = each.value.max_age } : {},
  )
}
# ---- END GENERATED resource spanning_tree_vlan_iosxe ----

