# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:d003c4bcca05...)
# Feature: system.features
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_features = flatten([
    for device in local.devices : [
      for feat_name, feat_enabled in try(local.device_config[device.name].feature, {}) : {
        key         = format("%s/feature/%s", device.name, feat_name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        leaf        = feat_name
      } if feat_enabled == true
    ]
  ])
}
# ---- END GENERATED locals ----

# ---- BEGIN GENERATED resource feature_nxos ----
resource "nso_device_config" "feature_nxos" {
  for_each = { for v in local.nso_system_features : v.key => v if v.os == "nxos" }

  instance   = each.value.instance
  device     = each.value.device_name
  path       = "tailf-ned-cisco-nx:feature/${each.value.leaf}"
  delete     = true
  attributes = {}
}
# ---- END GENERATED resource feature_nxos ----

