# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.enable_secret
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_enable_secret = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_enable_secret, []) : {
        key         = format("%s/enable_secret/%s", device.name, item.enable_secret)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        enable_secret  = item.enable_secret
        type             = try(item.type,
          null)
        secret           = try(item.secret,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource enable_secret_nxos ----
resource "nso_device_config" "enable_secret_nxos" {
  for_each = { for v in local.nso_aaa_enable_secret : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:enable/secret"
  delete   = false

  attributes = merge(
    { enable_secret = tostring(each.value.enable_secret) },
    each.value.type != null ? { "type" = each.value.type } : {},
    each.value.secret != null ? { "secret" = each.value.secret } : {},
  )
}
# ---- END GENERATED resource enable_secret_nxos ----
# ---- BEGIN GENERATED resource enable_secret_iosxe ----
resource "nso_device_config" "enable_secret_iosxe" {
  for_each = { for v in local.nso_aaa_enable_secret : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:enable/secret"
  delete   = false

  attributes = merge(
    { enable_secret = tostring(each.value.enable_secret) },
    each.value.type != null ? { "type" = each.value.type } : {},
    each.value.secret != null ? { "secret" = each.value.secret } : {},
  )
}
# ---- END GENERATED resource enable_secret_iosxe ----

