# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: evpn.instances
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_evpn_instances = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].evpn.instances, []) : {
        key         = format("%s/instance/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        vlan_based       = try(item.vlan_based,
          null)
        vlan_bundle      = try(item.vlan_bundle,
          null)
        rd               = try(item.rd,
          null)
        auto_route_target = try(item.auto_route_target,
          null)
        encapsulation_vxlan = try(item.encapsulation_vxlan,
          null)
        replication_type = try(item.replication_type,
          null)
        ip_local_learning = try(item.ip_local_learning,
          null)
        default_gateway_advertise = try(item.default_gateway_advertise,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource instance_iosxe ----
resource "nso_device_config" "instance_iosxe" {
  for_each = { for v in local.nso_evpn_instances : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:l2vpn-evpn/l2vpn/evpn/instance=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.vlan_based == true ? { "vlan-based" = "" } : {},
    each.value.vlan_bundle == true ? { "vlan-bundle" = "" } : {},
    each.value.rd != null ? { "rd" = each.value.rd } : {},
    each.value.auto_route_target != null ? { "auto-route-target" = each.value.auto_route_target } : {},
    each.value.encapsulation_vxlan == true ? { "encapsulation/vxlan" = "" } : {},
    each.value.replication_type != null ? { "replication-type" = each.value.replication_type } : {},
    each.value.ip_local_learning != null ? { "ip/local-learning" = each.value.ip_local_learning } : {},
    each.value.default_gateway_advertise != null ? { "default-gateway/advertise" = each.value.default_gateway_advertise } : {},
  )
}
# ---- END GENERATED resource instance_iosxe ----

