# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dns.global
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dns_global = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dns, []) : {
        key         = format("%s/global/%s", device.name, item.dns)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        dns  = item.dns
        domain_name      = try(item.domain_name,
          null)
        domain_lookup    = try(item.domain_lookup,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource global_nxos ----
resource "nso_device_config" "global_nxos" {
  for_each = { for v in local.nso_dns_global : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip"
  delete   = true

  attributes = merge(
    { ip = tostring(each.value.dns) },
    each.value.domain_name != null ? { "domain-name" = each.value.domain_name } : {},
    each.value.domain_lookup != null ? { "domain-lookup" = each.value.domain_lookup } : {},
  )
}
# ---- END GENERATED resource global_nxos ----
# ---- BEGIN GENERATED resource global_iosxe ----
resource "nso_device_config" "global_iosxe" {
  for_each = { for v in local.nso_dns_global : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/domain"
  delete   = true

  attributes = merge(
    { domain = tostring(each.value.dns) },
    each.value.domain_name != null ? { "name" = each.value.domain_name } : {},
    each.value.domain_lookup != null ? { "lookup-conf/lookup" = each.value.domain_lookup } : {},
  )
}
# ---- END GENERATED resource global_iosxe ----

