# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.snmp_communities
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_snmp_communities = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].snmp_communities, []) : {
        key         = format("%s/snmp_communitie/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        group            = try(item.group,
          null)
        use_acl          = try(item.use_acl,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource snmp_communitie_nxos ----
resource "nso_device_config" "snmp_communitie_nxos" {
  for_each = { for v in local.nso_system_snmp_communities : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:snmp-server/community=${each.value.name}"
  delete   = true

  attributes = merge(
    { snmp-community-string = tostring(each.value.name) },
    each.value.name != null ? { "snmp-community-string" = each.value.name } : {},
    each.value.group != null ? { "group" = each.value.group } : {},
    each.value.use_acl != null ? { "use-acl" = each.value.use_acl } : {},
  )
}
# ---- END GENERATED resource snmp_communitie_nxos ----
# ---- BEGIN GENERATED resource snmp_communitie_iosxe ----
resource "nso_device_config" "snmp_communitie_iosxe" {
  for_each = { for v in local.nso_system_snmp_communities : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:snmp-server/community=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource snmp_communitie_iosxe ----

