# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.spanning_tree
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_spanning_tree = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].spanning_tree, []) : {
        key         = format("%s/spanning_tree/%s", device.name, item.spanning_tree)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        spanning_tree  = item.spanning_tree
        mode             = try(item.mode,
          null)
        pathcost_method  = try(item.pathcost_method,
          null)
        logging          = try(item.logging,
          null)
        extend_system_id = try(item.extend_system_id,
          null)
        loopguard_default = try(item.loopguard_default,
          null)
        portfast_default = try(item.portfast_default,
          null)
        bpduguard_default = try(item.bpduguard_default,
          null)
        bpdufilter_default = try(item.bpdufilter_default,
          null)
        network_default  = try(item.network_default,
          null)
        bridge_assurance = try(item.bridge_assurance,
          null)
        lc_issu          = try(item.lc_issu,
          null)
        backbonefast     = try(item.backbonefast,
          null)
        uplinkfast       = try(item.uplinkfast,
          null)
        etherchannel_guard_misconfig = try(item.etherchannel_guard_misconfig,
          null)
        portfast_edge_default = try(item.portfast_edge_default,
          null)
        portfast_edge_bpduguard_default = try(item.portfast_edge_bpduguard_default,
          null)
        portfast_edge_bpdufilter_default = try(item.portfast_edge_bpdufilter_default,
          null)
        optimize_bpdu_transmission = try(item.optimize_bpdu_transmission,
          null)
        mst_forward_time = try(item.mst_forward_time,
          null)
        mst_hello_time   = try(item.mst_hello_time,
          null)
        mst_max_age      = try(item.mst_max_age,
          null)
        mst_max_hops     = try(item.mst_max_hops,
          null)
        mst_simulate_pvst = try(item.mst_simulate_pvst,
          null)
        mst_name         = try(item.mst_name,
          null)
        mst_revision     = try(item.mst_revision,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource spanning_tree_nxos ----
resource "nso_device_config" "spanning_tree_nxos" {
  for_each = { for v in local.nso_system_spanning_tree : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:spanning-tree"
  delete   = false

  attributes = merge(
    { spanning_tree = tostring(each.value.spanning_tree) },
    each.value.mode != null ? { "mode" = each.value.mode } : {},
    each.value.pathcost_method != null ? { "pathcost/method" = each.value.pathcost_method } : {},
    each.value.loopguard_default == true ? { "loopguard/default" = "" } : {},
    each.value.portfast_default == true ? { "port/type/edge/default" = "" } : {},
    each.value.bpduguard_default == true ? { "port/type/edge/bpduguard/default" = "" } : {},
    each.value.bpdufilter_default == true ? { "port/type/edge/bpdufilter/default" = "" } : {},
    each.value.network_default == true ? { "port/type/network/default" = "" } : {},
    each.value.bridge_assurance != null ? { "bridge/assurance" = each.value.bridge_assurance } : {},
    each.value.lc_issu != null ? { "lc-issu" = each.value.lc_issu } : {},
    each.value.mst_forward_time != null ? { "mst/forward-time" = each.value.mst_forward_time } : {},
    each.value.mst_hello_time != null ? { "mst/hello-time" = each.value.mst_hello_time } : {},
    each.value.mst_max_age != null ? { "mst/max-age" = each.value.mst_max_age } : {},
    each.value.mst_max_hops != null ? { "mst/max-hops" = each.value.mst_max_hops } : {},
    each.value.mst_simulate_pvst != null ? { "mst/simulate/pvst/global" = each.value.mst_simulate_pvst } : {},
    each.value.mst_name != null ? { "mst/configuration/name" = each.value.mst_name } : {},
    each.value.mst_revision != null ? { "mst/configuration/revision" = each.value.mst_revision } : {},
  )
}
# ---- END GENERATED resource spanning_tree_nxos ----
# ---- BEGIN GENERATED resource spanning_tree_iosxe ----
resource "nso_device_config" "spanning_tree_iosxe" {
  for_each = { for v in local.nso_system_spanning_tree : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:spanning-tree"
  delete   = false

  attributes = merge(
    { spanning_tree = tostring(each.value.spanning_tree) },
    each.value.mode != null ? { "mode" = each.value.mode } : {},
    each.value.pathcost_method != null ? { "pathcost/method" = each.value.pathcost_method } : {},
    each.value.logging == true ? { "logging" = "" } : {},
    each.value.extend_system_id == true ? { "extend/system-id" = "" } : {},
    each.value.loopguard_default == true ? { "loopguard/default" = "" } : {},
    each.value.portfast_default == true ? { "portfast/default" = "" } : {},
    each.value.bpduguard_default == true ? { "portfast/bpduguard/default" = "" } : {},
    each.value.bpdufilter_default == true ? { "portfast/bpdufilter/default" = "" } : {},
    each.value.backbonefast == true ? { "backbonefast" = "" } : {},
    each.value.uplinkfast == true ? { "uplinkfast" = "" } : {},
    each.value.etherchannel_guard_misconfig == true ? { "etherchannel/guard/misconfig" = "" } : {},
    each.value.portfast_edge_default == true ? { "portfast/edge/default" = "" } : {},
    each.value.portfast_edge_bpduguard_default == true ? { "portfast/edge/bpduguard/default" = "" } : {},
    each.value.portfast_edge_bpdufilter_default == true ? { "portfast/edge/bpdufilter/default" = "" } : {},
    each.value.optimize_bpdu_transmission != null ? { "optimize/bpdu/transmission" = each.value.optimize_bpdu_transmission } : {},
    each.value.mst_forward_time != null ? { "mst/forward-time" = each.value.mst_forward_time } : {},
    each.value.mst_name != null ? { "mst/configuration/name" = each.value.mst_name } : {},
    each.value.mst_revision != null ? { "mst/configuration/revision" = each.value.mst_revision } : {},
  )
}
# ---- END GENERATED resource spanning_tree_iosxe ----

