# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: evpn.global
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_evpn_global = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].evpn.global, []) : {
        key         = format("%s/global/%s", device.name, item.evpn_global)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        evpn_global  = item.evpn_global
        nv_overlay_evpn  = try(item.nv_overlay_evpn,
          null)
        anycast_gateway_mac = try(item.anycast_gateway_mac,
          null)
        vxlan_udp_port   = try(item.vxlan_udp_port,
          null)
        l2vpn_router_id  = try(item.l2vpn_router_id,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource global_nxos ----
resource "nso_device_config" "global_nxos" {
  for_each = { for v in local.nso_evpn_global : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:nv"
  delete   = false

  attributes = merge(
    { evpn_global = tostring(each.value.evpn_global) },
    each.value.nv_overlay_evpn == true ? { "overlay/evpn" = "" } : {},
    each.value.anycast_gateway_mac != null ? { "." = each.value.anycast_gateway_mac } : {},
  )
}
# ---- END GENERATED resource global_nxos ----
# ---- BEGIN GENERATED resource global_iosxe ----
resource "nso_device_config" "global_iosxe" {
  for_each = { for v in local.nso_evpn_global : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:vxlan"
  delete   = false

  attributes = merge(
    { evpn_global = tostring(each.value.evpn_global) },
    each.value.vxlan_udp_port != null ? { "udp/port" = each.value.vxlan_udp_port } : {},
    each.value.l2vpn_router_id != null ? { "." = each.value.l2vpn_router_id } : {},
  )
}
# ---- END GENERATED resource global_iosxe ----

