# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.server_groups_radius
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_server_groups_radius = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_server_groups_radius, []) : {
        key         = format("%s/server_groups_radiu/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        use_vrf          = try(item.use_vrf,
          null)
        deadtime         = try(item.deadtime,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource server_groups_radiu_nxos ----
resource "nso_device_config" "server_groups_radiu_nxos" {
  for_each = { for v in local.nso_aaa_server_groups_radius : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:aaa/group/server/radius=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.use_vrf != null ? { "use-vrf" = each.value.use_vrf } : {},
    each.value.deadtime != null ? { "deadtime" = each.value.deadtime } : {},
  )
}
# ---- END GENERATED resource server_groups_radiu_nxos ----
# ---- BEGIN GENERATED resource server_groups_radiu_iosxe ----
resource "nso_device_config" "server_groups_radiu_iosxe" {
  for_each = { for v in local.nso_aaa_server_groups_radius : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:aaa/group/server/radius=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.deadtime != null ? { "deadtime" = each.value.deadtime } : {},
  )
}
# ---- END GENERATED resource server_groups_radiu_iosxe ----

