# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: vrfs.af_ipv6_route_target_export
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_vrfs_af_ipv6_route_target_export = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].vrfs.af_ipv6_route_target_export, []) : {
        key         = format("%s/af_ipv6_route_target_export/%s", device.name, item.composite)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        composite  = item.composite
        method           = try(item.method,
          null)
        asn              = try(item.asn,
          null)
        target_evpn      = try(item.target_evpn,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource af_ipv6_route_target_export_nxos ----
resource "nso_device_config" "af_ipv6_route_target_export_nxos" {
  for_each = { for v in local.nso_vrfs_af_ipv6_route_target_export : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:vrf/context={id}/address-family/ipv6/unicast/route-target={method},{asn},{target-evpn}"
  delete   = true

  attributes = merge(
    { method,asn,target-evpn = tostring(each.value.composite) },
    each.value.method != null ? { "method" = each.value.method } : {},
    each.value.asn != null ? { "asn" = each.value.asn } : {},
    each.value.target_evpn != null ? { "target-evpn" = each.value.target_evpn } : {},
  )
}
# ---- END GENERATED resource af_ipv6_route_target_export_nxos ----
# ---- BEGIN GENERATED resource af_ipv6_route_target_export_iosxe ----
resource "nso_device_config" "af_ipv6_route_target_export_iosxe" {
  for_each = { for v in local.nso_vrfs_af_ipv6_route_target_export : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:vrf/definition={name}/address-family/ipv6/route-target/export={asn-ip}"
  delete   = true

  attributes = merge(
    { asn-ip = tostring(each.value.composite) },
    each.value.asn != null ? { "asn-ip" = each.value.asn } : {},
  )
}
# ---- END GENERATED resource af_ipv6_route_target_export_iosxe ----

