# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.ntp_servers
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_ntp_servers = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].ntp_servers, []) : {
        key         = format("%s/ntp_server/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        prefer           = try(item.prefer,
          null)
        key              = try(item.key,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ntp_server_nxos ----
resource "nso_device_config" "ntp_server_nxos" {
  for_each = { for v in local.nso_system_ntp_servers : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ntp/server=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.prefer == true ? { "prefer" = "" } : {},
    each.value.key != null ? { "key" = each.value.key } : {},
  )
}
# ---- END GENERATED resource ntp_server_nxos ----
# ---- BEGIN GENERATED resource ntp_server_iosxe ----
resource "nso_device_config" "ntp_server_iosxe" {
  for_each = { for v in local.nso_system_ntp_servers : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ntp/server/peer-list=${each.value.id}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.id) },
    each.value.id != null ? { "name" = each.value.id } : {},
    each.value.prefer == true ? { "prefer" = "" } : {},
    each.value.key != null ? { "key" = each.value.key } : {},
  )
}
# ---- END GENERATED resource ntp_server_iosxe ----

