# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: management.errdisable_recovery
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_management_errdisable_recovery = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].errdisable_recovery, []) : {
        key         = format("%s/errdisable_recovery/%s", device.name, item.errdisable_recovery)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        errdisable_recovery  = item.errdisable_recovery
        interval         = try(item.interval,
          null)
        cause_bpduguard  = try(item.cause_bpduguard,
          null)
        cause_link_flap  = try(item.cause_link_flap,
          null)
        cause_loopback   = try(item.cause_loopback,
          null)
        cause_udld       = try(item.cause_udld,
          null)
        cause_storm_control = try(item.cause_storm_control,
          null)
        cause_psecure_violation = try(item.cause_psecure_violation,
          null)
        cause_security_violation = try(item.cause_security_violation,
          null)
        cause_dhcp_rate_limit = try(item.cause_dhcp_rate_limit,
          null)
        cause_arp_inspection = try(item.cause_arp_inspection,
          null)
        cause_failed_port_state = try(item.cause_failed_port_state,
          null)
        cause_vpc_peerlink = try(item.cause_vpc_peerlink,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource errdisable_recovery_nxos ----
resource "nso_device_config" "errdisable_recovery_nxos" {
  for_each = { for v in local.nso_management_errdisable_recovery : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:errdisable/recovery"
  delete   = true

  attributes = merge(
    { recovery = tostring(each.value.errdisable_recovery) },
    each.value.interval != null ? { "interval" = each.value.interval } : {},
    each.value.cause_bpduguard == true ? { "cause/bpduguard" = "" } : {},
    each.value.cause_link_flap == true ? { "cause/link-flap" = "" } : {},
    each.value.cause_loopback == true ? { "cause/loopback" = "" } : {},
    each.value.cause_udld == true ? { "cause/udld" = "" } : {},
    each.value.cause_storm_control == true ? { "cause/storm-control" = "" } : {},
    each.value.cause_psecure_violation == true ? { "cause/psecure-violation" = "" } : {},
    each.value.cause_security_violation == true ? { "cause/security-violation" = "" } : {},
    each.value.cause_failed_port_state == true ? { "cause/failed-port-state" = "" } : {},
    each.value.cause_vpc_peerlink == true ? { "cause/vpc-peerlink" = "" } : {},
  )
}
# ---- END GENERATED resource errdisable_recovery_nxos ----
# ---- BEGIN GENERATED resource errdisable_recovery_iosxe ----
resource "nso_device_config" "errdisable_recovery_iosxe" {
  for_each = { for v in local.nso_management_errdisable_recovery : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:errdisable/recovery"
  delete   = true

  attributes = merge(
    { recovery = tostring(each.value.errdisable_recovery) },
    each.value.interval != null ? { "interval" = each.value.interval } : {},
    each.value.cause_bpduguard == true ? { "cause/bpduguard" = "" } : {},
    each.value.cause_link_flap == true ? { "cause/link-flap" = "" } : {},
    each.value.cause_loopback == true ? { "cause/loopback" = "" } : {},
    each.value.cause_udld == true ? { "cause/udld" = "" } : {},
    each.value.cause_storm_control == true ? { "cause/storm-control" = "" } : {},
    each.value.cause_psecure_violation == true ? { "cause/psecure-violation" = "" } : {},
    each.value.cause_security_violation == true ? { "cause/security-violation" = "" } : {},
    each.value.cause_dhcp_rate_limit == true ? { "cause/dhcp-rate-limit" = "" } : {},
    each.value.cause_arp_inspection == true ? { "cause/arp-inspection" = "" } : {},
  )
}
# ---- END GENERATED resource errdisable_recovery_iosxe ----

