# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: discovery.cdp
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_discovery_cdp = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].cdp, []) : {
        key         = format("%s/cdp/%s", device.name, item.cdp)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        cdp  = item.cdp
        enable           = try(item.enable,
          null)
        timer            = try(item.timer,
          null)
        holdtime         = try(item.holdtime,
          null)
        advertise_v2     = try(item.advertise_v2,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource cdp_nxos ----
resource "nso_device_config" "cdp_nxos" {
  for_each = { for v in local.nso_discovery_cdp : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:cdp"
  delete   = true

  attributes = merge(
    { cdp = tostring(each.value.cdp) },
    each.value.enable != null ? { "enable" = each.value.enable } : {},
    each.value.timer != null ? { "timer" = each.value.timer } : {},
    each.value.holdtime != null ? { "holdtime" = each.value.holdtime } : {},
  )
}
# ---- END GENERATED resource cdp_nxos ----
# ---- BEGIN GENERATED resource cdp_iosxe ----
resource "nso_device_config" "cdp_iosxe" {
  for_each = { for v in local.nso_discovery_cdp : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:cdp"
  delete   = true

  attributes = merge(
    { cdp = tostring(each.value.cdp) },
    each.value.enable != null ? { "run" = each.value.enable } : {},
    each.value.timer != null ? { "timer" = each.value.timer } : {},
    each.value.holdtime != null ? { "holdtime" = each.value.holdtime } : {},
    each.value.advertise_v2 != null ? { "advertise-v2" = each.value.advertise_v2 } : {},
  )
}
# ---- END GENERATED resource cdp_iosxe ----

