# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.accounting_exec
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_accounting_exec = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_accounting_exec, []) : {
        key         = format("%s/accounting_exec/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        action_type      = try(item.action_type,
          null)
        broadcast        = try(item.broadcast,
          null)
        group            = try(item.group,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource accounting_exec_iosxe ----
resource "nso_device_config" "accounting_exec_iosxe" {
  for_each = { for v in local.nso_aaa_accounting_exec : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:aaa/accounting/exec=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.action_type != null ? { "action-type" = each.value.action_type } : {},
    each.value.broadcast == true ? { "broadcast" = "" } : {},
    each.value.group != null ? { "group" = each.value.group } : {},
  )
}
# ---- END GENERATED resource accounting_exec_iosxe ----

