# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.global
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_global = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa, []) : {
        key         = format("%s/global/%s", device.name, item.aaa)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        aaa  = item.aaa
        new_model        = try(item.new_model,
          null)
        session_id       = try(item.session_id,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource global_nxos ----
resource "nso_device_config" "global_nxos" {
  for_each = { for v in local.nso_aaa_global : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:aaa"
  delete   = false

  attributes = merge(
    { aaa = tostring(each.value.aaa) },
  )
}
# ---- END GENERATED resource global_nxos ----
# ---- BEGIN GENERATED resource global_iosxe ----
resource "nso_device_config" "global_iosxe" {
  for_each = { for v in local.nso_aaa_global : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:aaa"
  delete   = false

  attributes = merge(
    { aaa = tostring(each.value.aaa) },
    each.value.new_model == true ? { "new-model" = "" } : {},
    each.value.session_id != null ? { "session-id" = each.value.session_id } : {},
  )
}
# ---- END GENERATED resource global_iosxe ----

