# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: evpn.vnis
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_evpn_vnis = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].evpn.vnis, []) : {
        key         = format("%s/vni/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        l2               = try(item.l2,
          null)
        rd               = try(item.rd,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource vni_nxos ----
resource "nso_device_config" "vni_nxos" {
  for_each = { for v in local.nso_evpn_vnis : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:evpn/vni=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.l2 == true ? { "l2" = "" } : {},
    each.value.rd != null ? { "rd" = each.value.rd } : {},
  )
}
# ---- END GENERATED resource vni_nxos ----

