# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.spanning_tree_mst_vlan_mapping
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_spanning_tree_mst_vlan_mapping = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].spanning_tree_mst_vlan_mapping, []) : {
        key         = format("%s/spanning_tree_mst_vlan_mapping/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        vlan             = try(item.vlan,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource spanning_tree_mst_vlan_mapping_iosxe ----
resource "nso_device_config" "spanning_tree_mst_vlan_mapping_iosxe" {
  for_each = { for v in local.nso_system_spanning_tree_mst_vlan_mapping : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:spanning-tree/mst/configuration/instance=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
    each.value.vlan != null ? { "vlan" = each.value.vlan } : {},
  )
}
# ---- END GENERATED resource spanning_tree_mst_vlan_mapping_iosxe ----

