# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: routing.route_maps
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_routing_route_maps = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].route_maps, []) : {
        key         = format("%s/route_map/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        sequence         = try(item.sequence,
          null)
        operation        = try(item.operation,
          null)
        description      = try(item.description,
          null)
        continue_sequence = try(item.continue_sequence,
          null)
        match_ip_address_prefix_lists = try(item.match_ip_address_prefix_lists,
          null)
        match_ip_next_hop_prefix_lists = try(item.match_ip_next_hop_prefix_lists,
          null)
        match_ipv6_address_prefix_lists = try(item.match_ipv6_address_prefix_lists,
          null)
        match_as_path    = try(item.match_as_path,
          null)
        match_community  = try(item.match_community,
          null)
        match_extcommunity = try(item.match_extcommunity,
          null)
        match_tag        = try(item.match_tag,
          null)
        match_route_type = try(item.match_route_type,
          null)
        match_interface  = try(item.match_interface,
          null)
        match_metric     = try(item.match_metric,
          null)
        match_source_protocol = try(item.match_source_protocol,
          null)
        set_local_preference = try(item.set_local_preference,
          null)
        set_metric_type  = try(item.set_metric_type,
          null)
        set_weight       = try(item.set_weight,
          null)
        set_tag          = try(item.set_tag,
          null)
        set_origin       = try(item.set_origin,
          null)
        set_distance     = try(item.set_distance,
          null)
        set_label_index  = try(item.set_label_index,
          null)
        set_nssa_only    = try(item.set_nssa_only,
          null)
        set_as_path_prepend = try(item.set_as_path_prepend,
          null)
        set_as_path_prepend_last_as = try(item.set_as_path_prepend_last_as,
          null)
        set_as_path_tag  = try(item.set_as_path_tag,
          null)
        set_ip_next_hop_peer_address = try(item.set_ip_next_hop_peer_address,
          null)
        set_level        = try(item.set_level,
          null)
        set_global       = try(item.set_global,
          null)
        set_vrf          = try(item.set_vrf,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource route_map_nxos ----
resource "nso_device_config" "route_map_nxos" {
  for_each = { for v in local.nso_routing_route_maps : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:route-map=${each.value.name},{sequence}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.sequence != null ? { "sequence" = each.value.sequence } : {},
    each.value.operation != null ? { "operation" = each.value.operation } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.continue_sequence != null ? { "continue" = each.value.continue_sequence } : {},
    each.value.match_ip_address_prefix_lists != null ? { "match/ip/address/prefix-list" = each.value.match_ip_address_prefix_lists } : {},
    each.value.match_ip_next_hop_prefix_lists != null ? { "match/ip/next-hop/prefix-list" = each.value.match_ip_next_hop_prefix_lists } : {},
    each.value.match_ipv6_address_prefix_lists != null ? { "match/ipv6/address/prefix-list" = each.value.match_ipv6_address_prefix_lists } : {},
    each.value.match_as_path != null ? { "match/as-path" = each.value.match_as_path } : {},
    each.value.match_community != null ? { "match/community" = each.value.match_community } : {},
    each.value.match_extcommunity != null ? { "match/extcommunity" = each.value.match_extcommunity } : {},
    each.value.match_tag != null ? { "match/tag" = each.value.match_tag } : {},
    each.value.match_route_type != null ? { "match/route-type" = each.value.match_route_type } : {},
    each.value.match_interface != null ? { "match/interface" = each.value.match_interface } : {},
    each.value.match_metric != null ? { "match/metric" = each.value.match_metric } : {},
    each.value.set_local_preference != null ? { "set/local-preference" = each.value.set_local_preference } : {},
    each.value.set_metric_type != null ? { "set/metric-type" = each.value.set_metric_type } : {},
    each.value.set_weight != null ? { "set/weight" = each.value.set_weight } : {},
    each.value.set_tag != null ? { "set/tag" = each.value.set_tag } : {},
    each.value.set_origin != null ? { "set/origin" = each.value.set_origin } : {},
    each.value.set_distance != null ? { "set/distance" = each.value.set_distance } : {},
    each.value.set_label_index != null ? { "set/label-index" = each.value.set_label_index } : {},
    each.value.set_nssa_only == true ? { "set/nssa-only" = "" } : {},
    each.value.set_as_path_prepend != null ? { "set/as-path/prepend/as-list" = each.value.set_as_path_prepend } : {},
    each.value.set_as_path_prepend_last_as != null ? { "set/as-path/prepend/last-as" = each.value.set_as_path_prepend_last_as } : {},
    each.value.set_as_path_tag == true ? { "set/as-path/tag" = "" } : {},
    each.value.set_ip_next_hop_peer_address == true ? { "set/ip/next-hop/peer-address" = "" } : {},
    each.value.set_vrf != null ? { "set/vrf" = each.value.set_vrf } : {},
  )
}
# ---- END GENERATED resource route_map_nxos ----
# ---- BEGIN GENERATED resource route_map_iosxe ----
resource "nso_device_config" "route_map_iosxe" {
  for_each = { for v in local.nso_routing_route_maps : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:route-map=${each.value.name},{sequence}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.sequence != null ? { "sequence" = each.value.sequence } : {},
    each.value.operation != null ? { "operation" = each.value.operation } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.continue_sequence != null ? { "continue/sequence-number" = each.value.continue_sequence } : {},
    each.value.match_ip_address_prefix_lists != null ? { "match/ip/address/prefix-list" = each.value.match_ip_address_prefix_lists } : {},
    each.value.match_ip_next_hop_prefix_lists != null ? { "match/ip/next-hop/prefix-list" = each.value.match_ip_next_hop_prefix_lists } : {},
    each.value.match_ipv6_address_prefix_lists != null ? { "match/ipv6/address/prefix-list" = each.value.match_ipv6_address_prefix_lists } : {},
    each.value.match_as_path != null ? { "match/as-path" = each.value.match_as_path } : {},
    each.value.match_community != null ? { "match/community" = each.value.match_community } : {},
    each.value.match_extcommunity != null ? { "match/extcommunity" = each.value.match_extcommunity } : {},
    each.value.match_tag != null ? { "match/tag" = each.value.match_tag } : {},
    each.value.match_route_type != null ? { "match/route-type" = each.value.match_route_type } : {},
    each.value.match_interface != null ? { "match/interface" = each.value.match_interface } : {},
    each.value.match_source_protocol != null ? { "match/source-protocol" = each.value.match_source_protocol } : {},
    each.value.set_local_preference != null ? { "set/local-preference/value" = each.value.set_local_preference } : {},
    each.value.set_metric_type != null ? { "set/metric-type" = each.value.set_metric_type } : {},
    each.value.set_weight != null ? { "set/weight" = each.value.set_weight } : {},
    each.value.set_tag != null ? { "set/tag" = each.value.set_tag } : {},
    each.value.set_origin != null ? { "set/origin/origin-value" = each.value.set_origin } : {},
    each.value.set_as_path_prepend != null ? { "set/as-path/prepend/as-list" = each.value.set_as_path_prepend } : {},
    each.value.set_as_path_prepend_last_as != null ? { "set/as-path/prepend/last-as" = each.value.set_as_path_prepend_last_as } : {},
    each.value.set_as_path_tag == true ? { "set/as-path/tag" = "" } : {},
    each.value.set_ip_next_hop_peer_address == true ? { "set/ip/next-hop/peer-address" = "" } : {},
    each.value.set_level != null ? { "set/level" = each.value.set_level } : {},
    each.value.set_global == true ? { "set/global" = "" } : {},
    each.value.set_vrf != null ? { "set/vrf" = each.value.set_vrf } : {},
  )
}
# ---- END GENERATED resource route_map_iosxe ----

