# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dhcp.snooping_vlans
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dhcp_snooping_vlans = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dhcp.snooping_vlans, []) : {
        key         = format("%s/snooping_vlan/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource snooping_vlan_nxos ----
resource "nso_device_config" "snooping_vlan_nxos" {
  for_each = { for v in local.nso_dhcp_snooping_vlans : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip/dhcp/snooping-config/snooping/vlan=${each.value.id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "id" = each.value.id } : {},
  )
}
# ---- END GENERATED resource snooping_vlan_nxos ----

