# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.line_vty
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_line_vty = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_line_vty, []) : {
        key         = format("%s/line_vty/%s", device.name, item.line_vty)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        line_vty  = item.line_vty
        first            = try(item.first,
          null)
        last             = try(item.last,
          null)
        exec_timeout_minutes = try(item.exec_timeout_minutes,
          null)
        exec_timeout_seconds = try(item.exec_timeout_seconds,
          null)
        exec_timeout     = try(item.exec_timeout,
          null)
        session_limit    = try(item.session_limit,
          null)
        login_local      = try(item.login_local,
          null)
        transport_input  = try(item.transport_input,
          null)
        transport_output = try(item.transport_output,
          null)
        authorization_exec = try(item.authorization_exec,
          null)
        accounting_exec  = try(item.accounting_exec,
          null)
        length           = try(item.length,
          null)
        width            = try(item.width,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource line_vty_nxos ----
resource "nso_device_config" "line_vty_nxos" {
  for_each = { for v in local.nso_aaa_line_vty : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:line/vty"
  delete   = true

  attributes = merge(
    { line_vty = tostring(each.value.line_vty) },
    each.value.exec_timeout != null ? { "exec-timeout" = each.value.exec_timeout } : {},
    each.value.session_limit != null ? { "session-limit" = each.value.session_limit } : {},
  )
}
# ---- END GENERATED resource line_vty_nxos ----
# ---- BEGIN GENERATED resource line_vty_iosxe ----
resource "nso_device_config" "line_vty_iosxe" {
  for_each = { for v in local.nso_aaa_line_vty : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:line/vty={first},{last}"
  delete   = true

  attributes = merge(
    { first = tostring(each.value.line_vty) },
    each.value.first != null ? { "first" = each.value.first } : {},
    each.value.last != null ? { "last" = each.value.last } : {},
    each.value.exec_timeout_minutes != null ? { "exec-timeout/minutes" = each.value.exec_timeout_minutes } : {},
    each.value.exec_timeout_seconds != null ? { "exec-timeout/seconds" = each.value.exec_timeout_seconds } : {},
    each.value.session_limit != null ? { "session-limit" = each.value.session_limit } : {},
    each.value.login_local == true ? { "login/local" = "" } : {},
    each.value.transport_input != null ? { "transport/input" = each.value.transport_input } : {},
    each.value.transport_output != null ? { "transport/output" = each.value.transport_output } : {},
    each.value.authorization_exec != null ? { "authorization/exec" = each.value.authorization_exec } : {},
    each.value.accounting_exec != null ? { "accounting/exec" = each.value.accounting_exec } : {},
    each.value.length != null ? { "length" = each.value.length } : {},
    each.value.width != null ? { "width" = each.value.width } : {},
  )
}
# ---- END GENERATED resource line_vty_iosxe ----

