# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dhcp.excluded_addresses
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dhcp_excluded_addresses = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dhcp.excluded_addresses, []) : {
        key         = format("%s/excluded_addresse/%s", device.name, item.low_address)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        low_address  = item.low_address
        low_address      = try(item.low_address,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource excluded_addresse_iosxe ----
resource "nso_device_config" "excluded_addresse_iosxe" {
  for_each = { for v in local.nso_dhcp_excluded_addresses : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/dhcp/excluded-address/low-list=${each.value.low_address}"
  delete   = true

  attributes = merge(
    { low = tostring(each.value.low_address) },
    each.value.low_address != null ? { "low" = each.value.low_address } : {},
  )
}
# ---- END GENERATED resource excluded_addresse_iosxe ----

