# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: management.clock_timezone
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_management_clock_timezone = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].clock_timezone, []) : {
        key         = format("%s/clock_timezone/%s", device.name, item.clock_timezone)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        clock_timezone  = item.clock_timezone
        zone             = try(item.zone,
          null)
        hours_offset     = try(item.hours_offset,
          null)
        minutes_offset   = try(item.minutes_offset,
          null)
        offset_sign      = try(item.offset_sign,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource clock_timezone_nxos ----
resource "nso_device_config" "clock_timezone_nxos" {
  for_each = { for v in local.nso_management_clock_timezone : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:clock/timezone"
  delete   = true

  attributes = merge(
    { timezone = tostring(each.value.clock_timezone) },
    each.value.zone != null ? { "name" = each.value.zone } : {},
    each.value.hours_offset != null ? { "hours-offset" = each.value.hours_offset } : {},
    each.value.minutes_offset != null ? { "minutes-offset" = each.value.minutes_offset } : {},
  )
}
# ---- END GENERATED resource clock_timezone_nxos ----
# ---- BEGIN GENERATED resource clock_timezone_iosxe ----
resource "nso_device_config" "clock_timezone_iosxe" {
  for_each = { for v in local.nso_management_clock_timezone : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:clock/timezone"
  delete   = true

  attributes = merge(
    { timezone = tostring(each.value.clock_timezone) },
    each.value.zone != null ? { "zone" = each.value.zone } : {},
    each.value.hours_offset != null ? { "hours" = each.value.hours_offset } : {},
    each.value.minutes_offset != null ? { "minutes" = each.value.minutes_offset } : {},
    each.value.offset_sign != null ? { "offset" = each.value.offset_sign } : {},
  )
}
# ---- END GENERATED resource clock_timezone_iosxe ----

