# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: dhcp.pools
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_dhcp_pools = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].dhcp.pools, []) : {
        key         = format("%s/pool/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        vrf              = try(item.vrf,
          null)
        network_number   = try(item.network_number,
          null)
        network_mask     = try(item.network_mask,
          null)
        default_router   = try(item.default_router,
          null)
        dns_server       = try(item.dns_server,
          null)
        domain_name      = try(item.domain_name,
          null)
        next_server      = try(item.next_server,
          null)
        netbios_name_server = try(item.netbios_name_server,
          null)
        netbios_node_type = try(item.netbios_node_type,
          null)
        bootfile         = try(item.bootfile,
          null)
        host_address     = try(item.host_address,
          null)
        host_mask        = try(item.host_mask,
          null)
        hardware_address = try(item.hardware_address,
          null)
        client_identifier = try(item.client_identifier,
          null)
        client_name      = try(item.client_name,
          null)
        lease_infinite   = try(item.lease_infinite,
          null)
        lease_days       = try(item.lease_days,
          null)
        lease_hours      = try(item.lease_hours,
          null)
        lease_minutes    = try(item.lease_minutes,
          null)
        update_arp       = try(item.update_arp,
          null)
        import_all       = try(item.import_all,
          null)
        accounting       = try(item.accounting,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource pool_iosxe ----
resource "nso_device_config" "pool_iosxe" {
  for_each = { for v in local.nso_dhcp_pools : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/dhcp/pool=${each.value.name}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.name) },
    each.value.name != null ? { "id" = each.value.name } : {},
    each.value.vrf != null ? { "vrf" = each.value.vrf } : {},
    each.value.network_number != null ? { "network/network-number" = each.value.network_number } : {},
    each.value.network_mask != null ? { "network/mask" = each.value.network_mask } : {},
    each.value.default_router != null ? { "default-router" = each.value.default_router } : {},
    each.value.dns_server != null ? { "dns-server" = each.value.dns_server } : {},
    each.value.domain_name != null ? { "domain-name" = each.value.domain_name } : {},
    each.value.next_server != null ? { "next-server" = each.value.next_server } : {},
    each.value.netbios_name_server != null ? { "netbios-name-server" = each.value.netbios_name_server } : {},
    each.value.netbios_node_type != null ? { "netbios-node-type" = each.value.netbios_node_type } : {},
    each.value.bootfile != null ? { "bootfile" = each.value.bootfile } : {},
    each.value.host_address != null ? { "host/address" = each.value.host_address } : {},
    each.value.host_mask != null ? { "host/mask" = each.value.host_mask } : {},
    each.value.hardware_address != null ? { "hardware-or-client/hardware-address/hardware-address" = each.value.hardware_address } : {},
    each.value.client_identifier != null ? { "hardware-or-client/client-identifier/client-identifier" = each.value.client_identifier } : {},
    each.value.client_name != null ? { "client-name" = each.value.client_name } : {},
    each.value.lease_infinite == true ? { "lease/lease-choice/a/infinite" = "" } : {},
    each.value.lease_days != null ? { "lease/lease-choice/b/days" = each.value.lease_days } : {},
    each.value.lease_hours != null ? { "lease/lease-choice/b/hours" = each.value.lease_hours } : {},
    each.value.lease_minutes != null ? { "lease/lease-choice/b/minutes" = each.value.lease_minutes } : {},
    each.value.update_arp == true ? { "update/arp" = "" } : {},
    each.value.import_all == true ? { "import/all" = "" } : {},
    each.value.accounting != null ? { "accounting" = each.value.accounting } : {},
  )
}
# ---- END GENERATED resource pool_iosxe ----

