# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: community_lists.expanded
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_community_lists_expanded = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].community_lists.expanded, []) : {
        key         = format("%s/expanded/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource expanded_nxos ----
resource "nso_device_config" "expanded_nxos" {
  for_each = { for v in local.nso_community_lists_expanded : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:ip/community-list/expanded=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource expanded_nxos ----
# ---- BEGIN GENERATED resource expanded_iosxe ----
resource "nso_device_config" "expanded_iosxe" {
  for_each = { for v in local.nso_community_lists_expanded : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:ip/community-list/expanded=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource expanded_iosxe ----

