# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:9bb33040adab...)
# Feature: system.hostname
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_hostname = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].hostname, []) : {
        key         = format("%s/hostname/%s", device.name, item.hostname)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        hostname  = item.hostname
        hostname         = try(item.hostname,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource hostname_nxos ----
resource "nso_device_config" "hostname_nxos" {
  for_each = { for v in local.nso_system_hostname : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:hostname"
  delete   = false

  attributes = merge(
    { hostname = tostring(each.value.hostname) },
    each.value.hostname != null ? { "." = each.value.hostname } : {},
  )
}
# ---- END GENERATED resource hostname_nxos ----
# ---- BEGIN GENERATED resource hostname_iosxe ----
resource "nso_device_config" "hostname_iosxe" {
  for_each = { for v in local.nso_system_hostname : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:hostname"
  delete   = false

  attributes = merge(
    { hostname = tostring(each.value.hostname) },
    each.value.hostname != null ? { "." = each.value.hostname } : {},
  )
}
# ---- END GENERATED resource hostname_iosxe ----

