# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.banner
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_banner = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].banner, []) : {
        key         = format("%s/banner/%s", device.name, item.banner)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        banner  = item.banner
        motd             = try(item.motd,
          null)
        login            = try(item.login,
          null)
        exec             = try(item.exec,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource banner_nxos ----
resource "nso_device_config" "banner_nxos" {
  for_each = { for v in local.nso_system_banner : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:banner"
  delete   = true

  attributes = merge(
    { banner = tostring(each.value.banner) },
    each.value.motd != null ? { "motd/message" = each.value.motd } : {},
    each.value.exec != null ? { "exec/message" = each.value.exec } : {},
  )
}
# ---- END GENERATED resource banner_nxos ----
# ---- BEGIN GENERATED resource banner_iosxe ----
resource "nso_device_config" "banner_iosxe" {
  for_each = { for v in local.nso_system_banner : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:banner"
  delete   = true

  attributes = merge(
    { banner = tostring(each.value.banner) },
    each.value.motd != null ? { "motd" = each.value.motd } : {},
    each.value.login != null ? { "login" = each.value.login } : {},
    each.value.exec != null ? { "exec" = each.value.exec } : {},
  )
}
# ---- END GENERATED resource banner_iosxe ----

