# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: qos.class_maps_qos
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_qos_class_maps_qos = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].qos.class_maps_qos, []) : {
        key         = format("%s/class_maps_qo/%s", device.name, item.name)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        name  = item.name
        name             = try(item.name,
          null)
        prematch         = try(item.prematch,
          null)
        description      = try(item.description,
          null)
        match_access_group_name = try(item.match_access_group_name,
          null)
        match_cos        = try(item.match_cos,
          null)
        match_dscp       = try(item.match_dscp,
          null)
        match_precedence = try(item.match_precedence,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource class_maps_qo_nxos ----
resource "nso_device_config" "class_maps_qo_nxos" {
  for_each = { for v in local.nso_qos_class_maps_qos : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:class-map/type/qos=${each.value.name}"
  delete   = true

  attributes = merge(
    { name = tostring(each.value.name) },
    each.value.name != null ? { "name" = each.value.name } : {},
    each.value.prematch != null ? { "prematch" = each.value.prematch } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.match_access_group_name != null ? { "match/access-group/name" = each.value.match_access_group_name } : {},
    each.value.match_cos != null ? { "match/cos" = each.value.match_cos } : {},
    each.value.match_dscp != null ? { "match/dscp" = each.value.match_dscp } : {},
    each.value.match_precedence != null ? { "match/precedence" = each.value.match_precedence } : {},
  )
}
# ---- END GENERATED resource class_maps_qo_nxos ----

