# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: interfaces.ethernets
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_interfaces_ethernets = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].interfaces.ethernets, []) : {
        key         = format("%s/ethernet/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        description      = try(item.description,
          null)
        shutdown         = try(item.shutdown,
          null)
        mtu              = try(item.mtu,
          null)
        switchport_mode  = try(item.switchport_mode,
          null)
        access_vlan      = try(item.access_vlan,
          null)
        trunk_native_vlan = try(item.trunk_native_vlan,
          null)
        channel_group_id = try(item.channel_group_id,
          null)
        channel_group_mode = try(item.channel_group_mode,
          null)
        vrf              = try(item.vrf,
          null)
        speed            = try(item.speed,
          null)
        duplex           = try(item.duplex,
          null)
        bandwidth        = try(item.bandwidth,
          null)
        delay            = try(item.delay,
          null)
        load_interval    = try(item.load_interval,
          null)
        mac_address      = try(item.mac_address,
          null)
        ipv4_address     = try(item.ipv4_address,
          null)
        ipv4_mask        = try(item.ipv4_mask,
          null)
        ip_proxy_arp     = try(item.ip_proxy_arp,
          null)
        ip_redirects     = try(item.ip_redirects,
          null)
        ip_unreachables  = try(item.ip_unreachables,
          null)
        ip_tcp_adjust_mss = try(item.ip_tcp_adjust_mss,
          null)
        trunk_allowed_vlans = try(item.trunk_allowed_vlans,
          null)
        spanning_tree_portfast = try(item.spanning_tree_portfast,
          null)
        spanning_tree_bpdufilter = try(item.spanning_tree_bpdufilter,
          null)
        spanning_tree_bpduguard = try(item.spanning_tree_bpduguard,
          null)
        spanning_tree_cost = try(item.spanning_tree_cost,
          null)
        spanning_tree_guard = try(item.spanning_tree_guard,
          null)
        spanning_tree_link_type = try(item.spanning_tree_link_type,
          null)
        spanning_tree_port_priority = try(item.spanning_tree_port_priority,
          null)
        lacp_port_priority = try(item.lacp_port_priority,
          null)
        lacp_rate        = try(item.lacp_rate,
          null)
        fec              = try(item.fec,
          null)
        logging_event_link_status = try(item.logging_event_link_status,
          null)
        cdp_enable       = try(item.cdp_enable,
          null)
        udld             = try(item.udld,
          null)
        flowcontrol_receive = try(item.flowcontrol_receive,
          null)
        flowcontrol_send = try(item.flowcontrol_send,
          null)
        medium           = try(item.medium,
          null)
        arp_timeout      = try(item.arp_timeout,
          null)
        service_policy_input = try(item.service_policy_input,
          null)
        service_policy_output = try(item.service_policy_output,
          null)
        vpc              = try(item.vpc,
          null)
        negotiation_auto = try(item.negotiation_auto,
          null)
        switchport_nonegotiate = try(item.switchport_nonegotiate,
          null)
        switchport_block_unicast = try(item.switchport_block_unicast,
          null)
        negotiate_auto   = try(item.negotiate_auto,
          null)
        media_type       = try(item.media_type,
          null)
        channel_protocol = try(item.channel_protocol,
          null)
        lldp_transmit    = try(item.lldp_transmit,
          null)
        lldp_receive     = try(item.lldp_receive,
          null)
        mdix_auto        = try(item.mdix_auto,
          null)
        storm_control_broadcast_level = try(item.storm_control_broadcast_level,
          null)
        storm_control_unicast_level = try(item.storm_control_unicast_level,
          null)
        storm_control_multicast_level = try(item.storm_control_multicast_level,
          null)
        storm_control_action_shutdown = try(item.storm_control_action_shutdown,
          null)
        storm_control_action_trap = try(item.storm_control_action_trap,
          null)
        switchport_trunk_encapsulation = try(item.switchport_trunk_encapsulation,
          null)
        ip_dhcp_snooping_trust = try(item.ip_dhcp_snooping_trust,
          null)
        ip_directed_broadcast = try(item.ip_directed_broadcast,
          null)
        ip_forward       = try(item.ip_forward,
          null)
        bfd_template     = try(item.bfd_template,
          null)
        keepalive        = try(item.keepalive,
          null)
        snmp_trap_link_status = try(item.snmp_trap_link_status,
          null)
        speed_group      = try(item.speed_group,
          null)
        beacon           = try(item.beacon,
          null)
        link_debounce_time = try(item.link_debounce_time,
          null)
        priority_flow_control_mode = try(item.priority_flow_control_mode,
          null)
        switchport_voice_vlan = try(item.switchport_voice_vlan,
          null)
        switchport_port_security = try(item.switchport_port_security,
          null)
        switchport_port_security_violation = try(item.switchport_port_security_violation,
          null)
        switchport_port_security_maximum = try(item.switchport_port_security_maximum,
          null)
        inherit_port_profile = try(item.inherit_port_profile,
          null)
        ip_ospf_cost     = try(item.ip_ospf_cost,
          null)
        ip_ospf_network_type = try(item.ip_ospf_network_type,
          null)
        ip_ospf_priority = try(item.ip_ospf_priority,
          null)
        ip_ospf_hello_interval = try(item.ip_ospf_hello_interval,
          null)
        ip_ospf_dead_interval = try(item.ip_ospf_dead_interval,
          null)
        ip_ospf_mtu_ignore = try(item.ip_ospf_mtu_ignore,
          null)
        ip_policy_route_map = try(item.ip_policy_route_map,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource ethernet_nxos ----
resource "nso_device_config" "ethernet_nxos" {
  for_each = { for v in local.nso_interfaces_ethernets : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:interface/Ethernet=${each.value.id}"
  delete   = false

  attributes = merge(
    { name = tostring(each.value.id) },
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.mtu != null ? { "mtu" = each.value.mtu } : {},
    each.value.switchport_mode != null ? { "switchport/mode" = each.value.switchport_mode } : {},
    each.value.access_vlan != null ? { "switchport/access/vlan" = each.value.access_vlan } : {},
    each.value.trunk_native_vlan != null ? { "switchport/trunk/native/vlan/vlan-id" = each.value.trunk_native_vlan } : {},
    each.value.channel_group_id != null ? { "channel-group/id" = each.value.channel_group_id } : {},
    each.value.channel_group_mode != null ? { "channel-group/mode" = each.value.channel_group_mode } : {},
    each.value.vrf != null ? { "vrf/member" = each.value.vrf } : {},
    each.value.speed != null ? { "speed" = each.value.speed } : {},
    each.value.duplex != null ? { "duplex" = each.value.duplex } : {},
    each.value.bandwidth != null ? { "bandwidth/bandwidth" = each.value.bandwidth } : {},
    each.value.delay != null ? { "delay" = each.value.delay } : {},
    each.value.load_interval != null ? { "load-interval/interval" = each.value.load_interval } : {},
    each.value.mac_address != null ? { "mac-address" = each.value.mac_address } : {},
    each.value.ipv4_address != null ? { "ip/static/address/ipaddr" = each.value.ipv4_address } : {},
    each.value.ip_proxy_arp == true ? { "ip/proxy-arp" = "" } : {},
    each.value.ip_redirects != null ? { "ip/redirects" = each.value.ip_redirects } : {},
    each.value.ip_unreachables == true ? { "ip/unreachables" = "" } : {},
    each.value.trunk_allowed_vlans != null ? { "switchport/trunk/allowed/vlan/ids" = each.value.trunk_allowed_vlans } : {},
    each.value.spanning_tree_portfast != null ? { "spanning-tree/port/type" = each.value.spanning_tree_portfast } : {},
    each.value.spanning_tree_bpdufilter != null ? { "spanning-tree/bpdufilter" = each.value.spanning_tree_bpdufilter } : {},
    each.value.spanning_tree_bpduguard != null ? { "spanning-tree/bpduguard" = each.value.spanning_tree_bpduguard } : {},
    each.value.spanning_tree_cost != null ? { "spanning-tree/cost" = each.value.spanning_tree_cost } : {},
    each.value.spanning_tree_guard != null ? { "spanning-tree/guard" = each.value.spanning_tree_guard } : {},
    each.value.spanning_tree_link_type != null ? { "spanning-tree/link-type" = each.value.spanning_tree_link_type } : {},
    each.value.spanning_tree_port_priority != null ? { "spanning-tree/port-priority" = each.value.spanning_tree_port_priority } : {},
    each.value.lacp_port_priority != null ? { "lacp/port-priority" = each.value.lacp_port_priority } : {},
    each.value.lacp_rate != null ? { "lacp/rate" = each.value.lacp_rate } : {},
    each.value.fec != null ? { "fec" = each.value.fec } : {},
    each.value.logging_event_link_status != null ? { "logging/event/port/linkstatus" = each.value.logging_event_link_status } : {},
    each.value.udld != null ? { "udld" = each.value.udld } : {},
    each.value.flowcontrol_receive != null ? { "flowcontrol/receive" = each.value.flowcontrol_receive } : {},
    each.value.flowcontrol_send != null ? { "flowcontrol/send" = each.value.flowcontrol_send } : {},
    each.value.medium != null ? { "medium" = each.value.medium } : {},
    each.value.arp_timeout != null ? { "ip/arp/timeout" = each.value.arp_timeout } : {},
    each.value.vpc != null ? { "vpc/port-channel-number" = each.value.vpc } : {},
    each.value.switchport_block_unicast == true ? { "switchport/block/unicast" = "" } : {},
    each.value.negotiate_auto != null ? { "negotiate/auto" = each.value.negotiate_auto } : {},
    each.value.mdix_auto != null ? { "mdix/auto" = each.value.mdix_auto } : {},
    each.value.storm_control_broadcast_level != null ? { "storm-control/broadcast/level" = each.value.storm_control_broadcast_level } : {},
    each.value.storm_control_unicast_level != null ? { "storm-control/unicast/level" = each.value.storm_control_unicast_level } : {},
    each.value.storm_control_multicast_level != null ? { "storm-control/multicast/level" = each.value.storm_control_multicast_level } : {},
    each.value.storm_control_action_shutdown == true ? { "storm-control/action/shutdown" = "" } : {},
    each.value.storm_control_action_trap == true ? { "storm-control/action/trap" = "" } : {},
    each.value.ip_dhcp_snooping_trust == true ? { "ip/dhcp/snooping/trust" = "" } : {},
    each.value.ip_directed_broadcast == true ? { "ip/directed-broadcast" = "" } : {},
    each.value.ip_forward == true ? { "ip/forward" = "" } : {},
    each.value.speed_group != null ? { "speed-group" = each.value.speed_group } : {},
    each.value.beacon == true ? { "beacon" = "" } : {},
    each.value.link_debounce_time != null ? { "link/debounce/time" = each.value.link_debounce_time } : {},
    each.value.priority_flow_control_mode != null ? { "priority-flow-control/mode" = each.value.priority_flow_control_mode } : {},
    each.value.switchport_voice_vlan != null ? { "switchport/voice/vlan" = each.value.switchport_voice_vlan } : {},
    each.value.switchport_port_security == true ? { "switchport/port-security-enable/port-security" = "" } : {},
    each.value.switchport_port_security_violation != null ? { "switchport/port-security/violation" = each.value.switchport_port_security_violation } : {},
    each.value.switchport_port_security_maximum != null ? { "switchport/port-security/maximum" = each.value.switchport_port_security_maximum } : {},
    each.value.inherit_port_profile != null ? { "inherit/port-profile" = each.value.inherit_port_profile } : {},
    each.value.ip_ospf_cost != null ? { "ip/ospf/cost" = each.value.ip_ospf_cost } : {},
    each.value.ip_ospf_network_type != null ? { "ip/ospf/network" = each.value.ip_ospf_network_type } : {},
    each.value.ip_ospf_priority != null ? { "ip/ospf/priority" = each.value.ip_ospf_priority } : {},
    each.value.ip_ospf_hello_interval != null ? { "ip/ospf/hello-interval" = each.value.ip_ospf_hello_interval } : {},
    each.value.ip_ospf_dead_interval != null ? { "ip/ospf/dead-interval" = each.value.ip_ospf_dead_interval } : {},
    each.value.ip_ospf_mtu_ignore == true ? { "ip/ospf/mtu-ignore" = "" } : {},
    each.value.ip_policy_route_map != null ? { "ip/policy/route-map" = each.value.ip_policy_route_map } : {},
  )
}
# ---- END GENERATED resource ethernet_nxos ----
# ---- BEGIN GENERATED resource ethernet_iosxe ----
resource "nso_device_config" "ethernet_iosxe" {
  for_each = { for v in local.nso_interfaces_ethernets : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:interface/GigabitEthernet=${each.value.id}"
  delete   = false

  attributes = merge(
    { name = tostring(each.value.id) },
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.mtu != null ? { "mtu" = each.value.mtu } : {},
    each.value.switchport_mode != null ? { "switchport/mode/access" = each.value.switchport_mode } : {},
    each.value.access_vlan != null ? { "switchport/access/vlan" = each.value.access_vlan } : {},
    each.value.trunk_native_vlan != null ? { "switchport/trunk/native/vlan" = each.value.trunk_native_vlan } : {},
    each.value.channel_group_id != null ? { "channel-group/number" = each.value.channel_group_id } : {},
    each.value.channel_group_mode != null ? { "channel-group/mode" = each.value.channel_group_mode } : {},
    each.value.vrf != null ? { "vrf/vrf/forwarding" = each.value.vrf } : {},
    each.value.speed != null ? { "speed" = each.value.speed } : {},
    each.value.duplex != null ? { "duplex" = each.value.duplex } : {},
    each.value.bandwidth != null ? { "bandwidth/kilobits" = each.value.bandwidth } : {},
    each.value.delay != null ? { "delay" = each.value.delay } : {},
    each.value.load_interval != null ? { "load-interval" = each.value.load_interval } : {},
    each.value.mac_address != null ? { "mac-address" = each.value.mac_address } : {},
    each.value.ipv4_address != null ? { "ip/address/address/fixed-case/primary/address" = each.value.ipv4_address } : {},
    each.value.ipv4_mask != null ? { "ip/address/address/fixed-case/primary/mask" = each.value.ipv4_mask } : {},
    each.value.ip_proxy_arp != null ? { "ip/proxy-arp" = each.value.ip_proxy_arp } : {},
    each.value.ip_redirects != null ? { "ip/redirects" = each.value.ip_redirects } : {},
    each.value.ip_unreachables != null ? { "ip/unreachables" = each.value.ip_unreachables } : {},
    each.value.ip_tcp_adjust_mss != null ? { "ip/tcp/adjust-mss" = each.value.ip_tcp_adjust_mss } : {},
    each.value.trunk_allowed_vlans != null ? { "switchport/trunk/allowed/vlan/vlans" = each.value.trunk_allowed_vlans } : {},
    each.value.spanning_tree_portfast != null ? { "spanning-tree/portfast" = each.value.spanning_tree_portfast } : {},
    each.value.spanning_tree_bpdufilter != null ? { "spanning-tree/bpdufilter" = each.value.spanning_tree_bpdufilter } : {},
    each.value.spanning_tree_bpduguard == true ? { "spanning-tree/bpduguard/enable" = "" } : {},
    each.value.spanning_tree_cost != null ? { "spanning-tree/cost" = each.value.spanning_tree_cost } : {},
    each.value.spanning_tree_guard != null ? { "spanning-tree/guard" = each.value.spanning_tree_guard } : {},
    each.value.spanning_tree_link_type != null ? { "spanning-tree/link-type" = each.value.spanning_tree_link_type } : {},
    each.value.spanning_tree_port_priority != null ? { "spanning-tree/port-priority" = each.value.spanning_tree_port_priority } : {},
    each.value.lacp_port_priority != null ? { "lacp/port-priority" = each.value.lacp_port_priority } : {},
    each.value.lacp_rate != null ? { "lacp/rate" = each.value.lacp_rate } : {},
    each.value.fec != null ? { "fec" = each.value.fec } : {},
    each.value.logging_event_link_status != null ? { "logging/event/link-status" = each.value.logging_event_link_status } : {},
    each.value.cdp_enable != null ? { "cdp/enable" = each.value.cdp_enable } : {},
    each.value.flowcontrol_receive != null ? { "flowcontrol/receive" = each.value.flowcontrol_receive } : {},
    each.value.flowcontrol_send != null ? { "flowcontrol/send" = each.value.flowcontrol_send } : {},
    each.value.medium != null ? { "medium" = each.value.medium } : {},
    each.value.arp_timeout != null ? { "arp/timeout" = each.value.arp_timeout } : {},
    each.value.service_policy_input != null ? { "service-policy/input" = each.value.service_policy_input } : {},
    each.value.service_policy_output != null ? { "service-policy/output" = each.value.service_policy_output } : {},
    each.value.negotiation_auto != null ? { "negotiation/auto" = each.value.negotiation_auto } : {},
    each.value.switchport_nonegotiate == true ? { "switchport/nonegotiate" = "" } : {},
    each.value.media_type != null ? { "media-type" = each.value.media_type } : {},
    each.value.channel_protocol != null ? { "channel-protocol" = each.value.channel_protocol } : {},
    each.value.lldp_transmit != null ? { "lldp/transmit" = each.value.lldp_transmit } : {},
    each.value.lldp_receive != null ? { "lldp/receive" = each.value.lldp_receive } : {},
    each.value.mdix_auto != null ? { "mdix/auto" = each.value.mdix_auto } : {},
    each.value.storm_control_broadcast_level != null ? { "." = each.value.storm_control_broadcast_level } : {},
    each.value.switchport_trunk_encapsulation != null ? { "switchport/trunk/encapsulation" = each.value.switchport_trunk_encapsulation } : {},
    each.value.bfd_template != null ? { "bfd/template" = each.value.bfd_template } : {},
    each.value.keepalive != null ? { "keepalive" = each.value.keepalive } : {},
    each.value.snmp_trap_link_status != null ? { "snmp/trap/link-status" = each.value.snmp_trap_link_status } : {},
    each.value.ip_ospf_cost != null ? { "ip/ospf/cost" = each.value.ip_ospf_cost } : {},
    each.value.ip_ospf_network_type != null ? { "ip/ospf/network" = each.value.ip_ospf_network_type } : {},
    each.value.ip_ospf_priority != null ? { "ip/ospf/priority" = each.value.ip_ospf_priority } : {},
    each.value.ip_ospf_hello_interval != null ? { "ip/ospf/hello-interval" = each.value.ip_ospf_hello_interval } : {},
    each.value.ip_ospf_dead_interval != null ? { "ip/ospf/dead-interval/seconds" = each.value.ip_ospf_dead_interval } : {},
    each.value.ip_ospf_mtu_ignore == true ? { "ip/ospf/mtu-ignore" = "" } : {},
    each.value.ip_policy_route_map != null ? { "ip/policy/route-map" = each.value.ip_policy_route_map } : {},
  )
}
# ---- END GENERATED resource ethernet_iosxe ----

