# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.tacacs_global
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_tacacs_global = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_tacacs_global, []) : {
        key         = format("%s/tacacs_global/%s", device.name, item.tacacs_global)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        tacacs_global  = item.tacacs_global
        timeout          = try(item.timeout,
          null)
        deadtime         = try(item.deadtime,
          null)
        directed_request = try(item.directed_request,
          null)
        key_type         = try(item.key_type,
          null)
        key_secret       = try(item.key_secret,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource tacacs_global_nxos ----
resource "nso_device_config" "tacacs_global_nxos" {
  for_each = { for v in local.nso_aaa_tacacs_global : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:tacacs-server"
  delete   = true

  attributes = merge(
    { tacacs_global = tostring(each.value.tacacs_global) },
    each.value.timeout != null ? { "timeout" = each.value.timeout } : {},
    each.value.deadtime != null ? { "deadtime" = each.value.deadtime } : {},
    each.value.directed_request == true ? { "directed-request" = "" } : {},
  )
}
# ---- END GENERATED resource tacacs_global_nxos ----
# ---- BEGIN GENERATED resource tacacs_global_iosxe ----
resource "nso_device_config" "tacacs_global_iosxe" {
  for_each = { for v in local.nso_aaa_tacacs_global : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:tacacs-server"
  delete   = true

  attributes = merge(
    { tacacs_global = tostring(each.value.tacacs_global) },
    each.value.timeout != null ? { "timeout" = each.value.timeout } : {},
    each.value.key_type != null ? { "key/type" = each.value.key_type } : {},
    each.value.key_secret != null ? { "key/secret" = each.value.key_secret } : {},
  )
}
# ---- END GENERATED resource tacacs_global_iosxe ----

