# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: fhrp.vrrp_groups
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_fhrp_vrrp_groups = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].fhrp.vrrp_groups, []) : {
        key         = format("%s/vrrp_group/%s", device.name, item.group_id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        group_id  = item.group_id
        ip_address       = try(item.ip_address,
          null)
        priority         = try(item.priority,
          null)
        preempt          = try(item.preempt,
          null)
        preempt_delay_minimum = try(item.preempt_delay_minimum,
          null)
        advertisement_interval = try(item.advertisement_interval,
          null)
        advertisement_interval_msec = try(item.advertisement_interval_msec,
          null)
        timer_learn      = try(item.timer_learn,
          null)
        authentication_text = try(item.authentication_text,
          null)
        authentication_word = try(item.authentication_word,
          null)
        shutdown         = try(item.shutdown,
          null)
        vrrpv2           = try(item.vrrpv2,
          null)
        description      = try(item.description,
          null)
        name             = try(item.name,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource vrrp_group_nxos ----
resource "nso_device_config" "vrrp_group_nxos" {
  for_each = { for v in local.nso_fhrp_vrrp_groups : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:interface/Vlan={interface_id}/vrrp=${each.value.group_id}"
  delete   = true

  attributes = merge(
    { vr = tostring(each.value.group_id) },
    each.value.ip_address != null ? { "address" = each.value.ip_address } : {},
    each.value.priority != null ? { "priority/value" = each.value.priority } : {},
    each.value.preempt == true ? { "preempt" = "" } : {},
    each.value.advertisement_interval != null ? { "advertisement-interval" = each.value.advertisement_interval } : {},
    each.value.authentication_text != null ? { "authentication/text" = each.value.authentication_text } : {},
    each.value.authentication_word != null ? { "authentication/word" = each.value.authentication_word } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
  )
}
# ---- END GENERATED resource vrrp_group_nxos ----
# ---- BEGIN GENERATED resource vrrp_group_iosxe ----
resource "nso_device_config" "vrrp_group_iosxe" {
  for_each = { for v in local.nso_fhrp_vrrp_groups : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:interface/Vlan={interface_id}/vrrp=${each.value.group_id}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.group_id) },
    each.value.ip_address != null ? { "ip/address" = each.value.ip_address } : {},
    each.value.priority != null ? { "priority" = each.value.priority } : {},
    each.value.preempt != null ? { "preempt" = each.value.preempt } : {},
    each.value.preempt_delay_minimum != null ? { "preempt/delay/minimum" = each.value.preempt_delay_minimum } : {},
    each.value.advertisement_interval != null ? { "timers/advertise/seconds" = each.value.advertisement_interval } : {},
    each.value.advertisement_interval_msec != null ? { "timers/advertise/msec" = each.value.advertisement_interval_msec } : {},
    each.value.timer_learn == true ? { "timers/learn" = "" } : {},
    each.value.authentication_text != null ? { "authentication/text" = each.value.authentication_text } : {},
    each.value.authentication_word != null ? { "authentication/word" = each.value.authentication_word } : {},
    each.value.shutdown == true ? { "shutdown" = "" } : {},
    each.value.vrrpv2 == true ? { "vrrpv2" = "" } : {},
    each.value.description != null ? { "description" = each.value.description } : {},
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource vrrp_group_iosxe ----

