# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: vrfs.route_target_export
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_vrfs_route_target_export = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].vrfs.route_target_export, []) : {
        key         = format("%s/route_target_export/%s", device.name, item.composite)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        composite  = item.composite
        asn_ip           = try(item.asn_ip,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource route_target_export_iosxe ----
resource "nso_device_config" "route_target_export_iosxe" {
  for_each = { for v in local.nso_vrfs_route_target_export : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:vrf/definition={name}/route-target/export={asn-ip}"
  delete   = true

  attributes = merge(
    { asn-ip = tostring(each.value.composite) },
    each.value.asn_ip != null ? { "asn-ip" = each.value.asn_ip } : {},
  )
}
# ---- END GENERATED resource route_target_export_iosxe ----

