# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: fhrp.hsrp_groups
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_fhrp_hsrp_groups = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].fhrp.hsrp_groups, []) : {
        key         = format("%s/hsrp_group/%s", device.name, item.group_id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        group_id  = item.group_id
        address_family   = try(item.address_family,
          null)
        ip_address       = try(item.ip_address,
          null)
        priority         = try(item.priority,
          null)
        preempt          = try(item.preempt,
          null)
        preempt_delay_minimum = try(item.preempt_delay_minimum,
          null)
        preempt_delay_reload = try(item.preempt_delay_reload,
          null)
        preempt_delay_sync = try(item.preempt_delay_sync,
          null)
        hello_interval_seconds = try(item.hello_interval_seconds,
          null)
        hello_interval_msec = try(item.hello_interval_msec,
          null)
        hold_time_seconds = try(item.hold_time_seconds,
          null)
        hold_time_msec   = try(item.hold_time_msec,
          null)
        authentication_text = try(item.authentication_text,
          null)
        authentication_word = try(item.authentication_word,
          null)
        authentication_md5_key_chain = try(item.authentication_md5_key_chain,
          null)
        mac_address      = try(item.mac_address,
          null)
        follow           = try(item.follow,
          null)
        name             = try(item.name,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource hsrp_group_nxos ----
resource "nso_device_config" "hsrp_group_nxos" {
  for_each = { for v in local.nso_fhrp_hsrp_groups : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:interface/Vlan={interface_id}/hsrp/hsrp-list=${each.value.group_id},{address_family}"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.group_id) },
    each.value.address_family != null ? { "addr_type" = each.value.address_family } : {},
    each.value.ip_address != null ? { "ip/address" = each.value.ip_address } : {},
    each.value.priority != null ? { "priority" = each.value.priority } : {},
    each.value.preempt != null ? { "preempt" = each.value.preempt } : {},
    each.value.preempt_delay_minimum != null ? { "preempt/delay/minimum" = each.value.preempt_delay_minimum } : {},
    each.value.preempt_delay_reload != null ? { "preempt/delay/reload" = each.value.preempt_delay_reload } : {},
    each.value.preempt_delay_sync != null ? { "preempt/delay/sync" = each.value.preempt_delay_sync } : {},
    each.value.hello_interval_seconds != null ? { "timers/hello-seconds" = each.value.hello_interval_seconds } : {},
    each.value.hello_interval_msec != null ? { "timers/hello-msec" = each.value.hello_interval_msec } : {},
    each.value.hold_time_seconds != null ? { "timers/hold-seconds" = each.value.hold_time_seconds } : {},
    each.value.hold_time_msec != null ? { "timers/hold-msec" = each.value.hold_time_msec } : {},
    each.value.authentication_text != null ? { "authentication/text" = each.value.authentication_text } : {},
    each.value.authentication_md5_key_chain != null ? { "authentication/md5" = each.value.authentication_md5_key_chain } : {},
    each.value.mac_address != null ? { "mac-address" = each.value.mac_address } : {},
    each.value.follow != null ? { "follow" = each.value.follow } : {},
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource hsrp_group_nxos ----
# ---- BEGIN GENERATED resource hsrp_group_iosxe ----
resource "nso_device_config" "hsrp_group_iosxe" {
  for_each = { for v in local.nso_fhrp_hsrp_groups : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:interface/Vlan={interface_id}/standby/standby-list=${each.value.group_id}"
  delete   = true

  attributes = merge(
    { group-number = tostring(each.value.group_id) },
    each.value.ip_address != null ? { "ip/address" = each.value.ip_address } : {},
    each.value.priority != null ? { "priority" = each.value.priority } : {},
    each.value.preempt != null ? { "preempt" = each.value.preempt } : {},
    each.value.preempt_delay_minimum != null ? { "preempt/delay/minimum" = each.value.preempt_delay_minimum } : {},
    each.value.preempt_delay_reload != null ? { "preempt/delay/reload" = each.value.preempt_delay_reload } : {},
    each.value.preempt_delay_sync != null ? { "preempt/delay/sync" = each.value.preempt_delay_sync } : {},
    each.value.hello_interval_seconds != null ? { "timers/hello-interval/seconds" = each.value.hello_interval_seconds } : {},
    each.value.hello_interval_msec != null ? { "timers/hello-interval/msec" = each.value.hello_interval_msec } : {},
    each.value.hold_time_seconds != null ? { "timers/hold-time/seconds" = each.value.hold_time_seconds } : {},
    each.value.hold_time_msec != null ? { "timers/hold-time/msec" = each.value.hold_time_msec } : {},
    each.value.authentication_text != null ? { "authentication/text" = each.value.authentication_text } : {},
    each.value.authentication_word != null ? { "authentication/word" = each.value.authentication_word } : {},
    each.value.authentication_md5_key_chain != null ? { "authentication/md5" = each.value.authentication_md5_key_chain } : {},
    each.value.mac_address != null ? { "mac-address" = each.value.mac_address } : {},
    each.value.follow != null ? { "follow" = each.value.follow } : {},
    each.value.name != null ? { "name" = each.value.name } : {},
  )
}
# ---- END GENERATED resource hsrp_group_iosxe ----

