# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: aaa.line_console
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_aaa_line_console = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].aaa_line_console, []) : {
        key         = format("%s/line_console/%s", device.name, item.line_console)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        line_console  = item.line_console
        exec_timeout_minutes = try(item.exec_timeout_minutes,
          null)
        exec_timeout_seconds = try(item.exec_timeout_seconds,
          null)
        exec_timeout     = try(item.exec_timeout,
          null)
        privilege_level  = try(item.privilege_level,
          null)
        login_local      = try(item.login_local,
          null)
        transport_input  = try(item.transport_input,
          null)
        transport_output = try(item.transport_output,
          null)
        stopbits         = try(item.stopbits,
          null)
        length           = try(item.length,
          null)
        width            = try(item.width,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource line_console_nxos ----
resource "nso_device_config" "line_console_nxos" {
  for_each = { for v in local.nso_aaa_line_console : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:line/console"
  delete   = true

  attributes = merge(
    { line_console = tostring(each.value.line_console) },
    each.value.exec_timeout != null ? { "exec-timeout" = each.value.exec_timeout } : {},
    each.value.privilege_level != null ? { "privilege/level" = each.value.privilege_level } : {},
  )
}
# ---- END GENERATED resource line_console_nxos ----
# ---- BEGIN GENERATED resource line_console_iosxe ----
resource "nso_device_config" "line_console_iosxe" {
  for_each = { for v in local.nso_aaa_line_console : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:line/console"
  delete   = true

  attributes = merge(
    { first = tostring(each.value.line_console) },
    each.value.exec_timeout_minutes != null ? { "exec-timeout/minutes" = each.value.exec_timeout_minutes } : {},
    each.value.exec_timeout_seconds != null ? { "exec-timeout/seconds" = each.value.exec_timeout_seconds } : {},
    each.value.privilege_level != null ? { "privilege/level" = each.value.privilege_level } : {},
    each.value.login_local == true ? { "login/local" = "" } : {},
    each.value.transport_input != null ? { "transport/input" = each.value.transport_input } : {},
    each.value.transport_output != null ? { "transport/output" = each.value.transport_output } : {},
    each.value.stopbits != null ? { "stopbits" = each.value.stopbits } : {},
    each.value.length != null ? { "length" = each.value.length } : {},
    each.value.width != null ? { "width" = each.value.width } : {},
  )
}
# ---- END GENERATED resource line_console_iosxe ----

