# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.logging
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_logging = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].logging, []) : {
        key         = format("%s/logging/%s", device.name, item.logging)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        logging  = item.logging
        source_interface = try(item.source_interface,
          null)
        timestamp        = try(item.timestamp,
          null)
        monitor          = try(item.monitor,
          null)
        console          = try(item.console,
          null)
        rate_limit       = try(item.rate_limit,
          null)
        userinfo         = try(item.userinfo,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource logging_nxos ----
resource "nso_device_config" "logging_nxos" {
  for_each = { for v in local.nso_system_logging : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:logging"
  delete   = true

  attributes = merge(
    { logging = tostring(each.value.logging) },
    each.value.source_interface != null ? { "source-interface" = each.value.source_interface } : {},
    each.value.timestamp != null ? { "timestamp" = each.value.timestamp } : {},
    each.value.monitor != null ? { "monitor" = each.value.monitor } : {},
    each.value.console != null ? { "console" = each.value.console } : {},
    each.value.rate_limit != null ? { "rate-limit" = each.value.rate_limit } : {},
  )
}
# ---- END GENERATED resource logging_nxos ----
# ---- BEGIN GENERATED resource logging_iosxe ----
resource "nso_device_config" "logging_iosxe" {
  for_each = { for v in local.nso_system_logging : v.key => v if v.os == "iosxe" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-ios:logging"
  delete   = true

  attributes = merge(
    { logging = tostring(each.value.logging) },
    each.value.userinfo == true ? { "userinfo" = "" } : {},
  )
}
# ---- END GENERATED resource logging_iosxe ----

