# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: system.logging_servers
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_system_logging_servers = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].logging_servers, []) : {
        key         = format("%s/logging_server/%s", device.name, item.host)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        host  = item.host
        host             = try(item.host,
          null)
        level            = try(item.level,
          null)
        port             = try(item.port,
          null)
        facility         = try(item.facility,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource logging_server_nxos ----
resource "nso_device_config" "logging_server_nxos" {
  for_each = { for v in local.nso_system_logging_servers : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:logging/server=${each.value.host}"
  delete   = true

  attributes = merge(
    { host = tostring(each.value.host) },
    each.value.host != null ? { "host" = each.value.host } : {},
    each.value.level != null ? { "level" = each.value.level } : {},
    each.value.port != null ? { "port" = each.value.port } : {},
    each.value.facility != null ? { "facility" = each.value.facility } : {},
  )
}
# ---- END GENERATED resource logging_server_nxos ----

