# GENERATED BY nac-nso-generator v0.1.0
# NED: cisco-ios-cli-6.115, cisco-nx-cli-5.37
# Mapping: mapping.yaml (sha256:da7dc6890f83...)
# Feature: qos.system_qos
#
# Code between BEGIN/END GENERATED markers is regenerated.
# Everything outside markers is manual and preserved across runs.


# ---- BEGIN GENERATED locals ----
locals {
  nso_qos_system_qos = flatten([
    for device in local.devices : [
      for item in try(local.device_config[device.name].qos.system_qos, []) : {
        key         = format("%s/system_qo/%s", device.name, item.id)
        device_name = device.name
        instance    = device.name
        os          = try(device.os, "iosxe")
        id  = item.id
        id               = try(item.id,
          null)
        network_qos_policy = try(item.network_qos_policy,
          null)
        qos_input_policy = try(item.qos_input_policy,
          null)
        queuing_input_policy = try(item.queuing_input_policy,
          null)
        queuing_output_policy = try(item.queuing_output_policy,
          null)
      }
    ]
  ])
}
# ---- END GENERATED locals ----


# ---- BEGIN GENERATED resource system_qo_nxos ----
resource "nso_device_config" "system_qo_nxos" {
  for_each = { for v in local.nso_qos_system_qos : v.key => v if v.os == "nxos" }

  instance = each.value.instance
  device   = each.value.device_name
  path     = "tailf-ned-cisco-nx:system/qos/service-policy"
  delete   = true

  attributes = merge(
    { id = tostring(each.value.id) },
    each.value.id != null ? { "." = each.value.id } : {},
    each.value.network_qos_policy != null ? { "type/network-qos" = each.value.network_qos_policy } : {},
    each.value.qos_input_policy != null ? { "type/qos/input" = each.value.qos_input_policy } : {},
    each.value.queuing_input_policy != null ? { "type/queuing/input" = each.value.queuing_input_policy } : {},
    each.value.queuing_output_policy != null ? { "type/queuing/output" = each.value.queuing_output_policy } : {},
  )
}
# ---- END GENERATED resource system_qo_nxos ----

